const items = [
  // 地名
  {'Id':'', 'Galar':'GALAJ', 'Trance':'GALAR', 'Comment':'ガラル', 'Type':'地名'},
  {'Id':'', 'Galar':'CFSR', 'Trance':'', 'Comment':'ハロンタウン', 'Type':'地名'},
  {'Id':'', 'Galar':'XHEDDY', 'Trance':'BRASSY', 'Comment':'ブラッシータウン', 'Type':'地名'},
  {'Id':'', 'Galar':'KOYXOH', 'Trance':'ENGINE', 'Comment':'エンジンシティ \n Eに当たる文字が違うのは、 \nアラビア語等に見られる語頭形・語尾形か', 'Type':'地名'},
  {'Id':'', 'Galar':'VUDF', 'Trance':'TURF', 'Comment':'ターフタウン', 'Type':'地名'},
  {'Id':'', 'Galar':'WCA', 'Trance':'BOW', 'Comment':'バウタウン \nBowは船首の意', 'Type':'地名'},
  {'Id':'', 'Galar':'MDEBCFA', 'Trance':'KNUCKLE', 'Comment':'ナックルシティ \nKnuckleは関節の意', 'Type':'地名'},
  {'Id':'', 'Galar':'TRNBOK', 'Trance':'', 'Comment':'ラテラルタウン', 'Type':'地名'},
  {'Id':'', 'Galar':'LYEXA', 'Trance':'あらべすく(音節) \nARBSQ(TDN)', 'Comment':'アラベスクタウン \nアラベスクは英語で「アラビアの」という意 \nアラビア語は子音だけを書くアブジャド', 'Type':'地名'},
  {'Id':'', 'Galar':'KHMTOR', 'Trance':'CIRCUS(羅)', 'Comment':'キルクスタウン \n戦車競技場', 'Type':'地名'},
  {'Id':'', 'Galar':'WSILYJ', 'Trance':'', 'Comment':'スパイクタウン', 'Type':'地名'},
  {'Id':'', 'Galar':'AECIIJT', 'Trance':'', 'Comment':'シュートシティ', 'Type':'地名'},

  // 人名
  {'Id':'', 'Galar':'ROSH', 'Trance':'ROSE', 'Comment':'ローズ', 'Type':'人名'},
  {'Id':'', 'Galar':'DCVDB', 'Trance':'DANDE', 'Comment':'ダンデ', 'Type':'人名'},
  {'Id':'', 'Galar':'EOU', 'Trance':'HOP', 'Comment':'ホップ', 'Type':'人名'},
  {'Id':'', 'Galar':'MVRY', 'Trance':'MARY', 'Comment':'マリィ', 'Type':'人名'},
  {'Id':'', 'Galar':'OeeJ', 'Trance':'BEET', 'Comment':'ビート', 'Type':'人名'},
  {'Id':'', 'Galar':'LJOOAW', 'Trance':'YALLOW', 'Comment':'ヤロー', 'Type':'人名'},
  {'Id':'', 'Galar':'UVUK', 'Trance':'', 'Comment':'ルリナ', 'Type':'人名'},
  {'Id':'', 'Galar':'RVDS', 'Trance':'KABU', 'Comment':'カブ', 'Type':'人名'},
  {'Id':'', 'Galar':'SVFJU', 'Trance':'', 'Comment':'サイトウ', 'Type':'人名'},
  {'Id':'', 'Galar':'CeICe', 'Trance':'ONION', 'Comment':'オニオン', 'Type':'人名'},
  {'Id':'', 'Galar':'', 'Trance':'POPLAR', 'Comment':'ポプラ', 'Type':'人名'},
  {'Id':'', 'Galar':'NBRVBY', 'Trance':'MAKUWA', 'Comment':'マクワ', 'Type':'人名'},
  {'Id':'', 'Galar':'WHKOV', 'Trance':'MELON', 'Comment':'メロン', 'Type':'人名'},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'ネズ', 'Type':'人名'},
  {'Id':'', 'Galar':'YINJEJ', 'Trance':'KIBANA', 'Comment':'キバナ', 'Type':'人名'},
  {'Id':'', 'Galar':'OKUEUE', 'Trance':'KURARA', 'Comment':'クララ', 'Type':'人名'},
  {'Id':'', 'Galar':'EAJUOTL', 'Trance':'SAVERIO(独)', 'Comment':'セイボリー', 'Type':'人名'},
  {'Id':'', 'Galar':'FUAWeOS', 'Trance':'MITSUBA', 'Comment':'ミツバ', 'Type':'人名'},
  {'Id':'', 'Galar':'BhLLCli', 'Trance':'BALLGuy', 'Comment':'ボールガイ', 'Type':'人名'},
  {'Id':'', 'Galar':'VKIOLYVL', 'Trance':'ACHERNAR(剌)', 'Comment':'アケルナル', 'Type':'人名'},
  {'Id':'', 'Galar':'SOeXIBBU', 'Trance':'DSCHUBBA(剌)', 'Comment':'ジュバ', 'Type':'人名'},
  {'Id':'', 'Galar':'JeFCWKE', 'Trance':'POLARIS(羅)', 'Comment':'ポラリス', 'Type':'人名'},
  {'Id':'', 'Galar':'XKY', 'Trance':'WEI(中)', 'Comment':'ウェイ', 'Type':'人名'},
  {'Id':'', 'Galar':'DANOYe', 'Trance':'KENGYU(日)', 'Comment':'ケンギュウ', 'Type':'人名'},
  {'Id':'', 'Galar':'LBNBDEVA', 'Trance':'DENEBOLA(剌)', 'Comment':'デネボラ', 'Type':'人名'},
  {'Id':'', 'Galar':'EKDWVS', 'Trance':'BIRDUN(剌)', 'Comment':'バーダン', 'Type':'人名'},
  {'Id':'', 'Galar':'OeUReUF', 'Trance':'MENKENT(剌・羅)', 'Comment':'メンケント', 'Type':'人名'},
  {'Id':'', 'Galar':'RHLC', 'Trance':'CAPH(剌)', 'Comment':'カフ', 'Type':'人名'},
  {'Id':'', 'Galar':'WFKXYI', 'Trance':'GIENAH(剌)', 'Comment':'ギェナー', 'Type':'人名'},
  {'Id':'', 'Galar':'UNYO', 'Trance':'IZAR(剌)', 'Comment':'イザル', 'Type':'人名'},
  {'Id':'', 'Galar':'CSB', 'Trance':'YUE(中)', 'Comment':'ユエ', 'Type':'人名'},
  {'Id':'', 'Galar':'AYUYRYLC', 'Trance':'MATAHARI(馬)', 'Comment':'マタハリ', 'Type':'人名'},
  {'Id':'', 'Galar':'MRFEFSD', 'Trance':'ORIHIME(日)', 'Comment':'オリヒメ', 'Type':'人名'},
  {'Id':'', 'Galar':'IENNWAJ', 'Trance':'THEEMIN', 'Comment':'テーミン', 'Type':'人名'},

  // ユニフォーム
  {'Id':'', 'Galar':'SeeC chqllingi', 'Trance':'SEED Challenge', 'Comment':'チャレンジセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'WCSh', 'Trance':'KUSA', 'Comment':'くさセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'BKSe', 'Trance':'MIZU', 'Comment':'みずセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'IOWO', 'Trance':'HONO', 'Comment':'ほのおセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'OCET', 'Trance':'', 'Comment':'ゴーストセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'RFESBLO', 'Trance':'KAKUTOU', 'Comment':'かくとうセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'EHIOT', 'Trance':'FAIRY', 'Comment':'フェアリーセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'TMY', 'Trance':'IWA', 'Comment':'いわセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'BDeY', 'Trance':'', 'Comment':'こおりセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'JWE', 'Trance':'AKU', 'Comment':'あくセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'MLKDUA', 'Trance':'DRAGON', 'Comment':'ドラゴンセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'CVSLI', 'Trance':'', 'Comment':'むしセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'CYDYUH', 'Trance':'HAGANE', 'Comment':'はがねセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'IEOeU', 'Trance':'PSICO(伊)', 'Comment':'エスパーセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'UEXMF', 'Trance':'DENKI', 'Comment':'でんきセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'LFCBN', 'Trance':'JIMEN', 'Comment':'じめんセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'XFRUK', 'Trance':'HIKOU', 'Comment':'ひこうセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'XUTXVF', 'Trance':'NORMAL', 'Comment':'ノーマルセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'JNHV', 'Trance':'DOKU', 'Comment':'どくセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'Whtdplon', 'Trance':'Champion', 'Comment':'チャンピオンセット', 'Type':'ユニフォーム'},
  {'Id':'', 'Galar':'NJAO', 'Trance':'', 'Comment':'ランクバトルセット', 'Type':'ユニフォーム'},

  // 薄明の翼
  {'Id':'', 'Galar':'DNoM hqlJNo', 'Trance':'', 'Comment':'ダンデのポスター上', 'Type':'薄明の翼1話'},
  {'Id':'', 'Galar':'Jq? OrfkoM', 'Trance':'', 'Comment':'ダンデのポスター下', 'Type':'薄明の翼1話'},
  {'Id':'', 'Galar':'BEKCVE', 'Trance':'', 'Comment':'ダンデのポスター2', 'Type':'薄明の翼1話'},
  {'Id':'', 'Galar':'GALAJ', 'Trance':'', 'Comment':'ダンデのポスター2', 'Type':'薄明の翼1話'},
  {'Id':'', 'Galar':'Dfkcq', 'Trance':'', 'Comment':'ダンデのポスター2', 'Type':'薄明の翼1話'},
  {'Id':'', 'Galar':'Xh Rlq Kgcrmfki', 'Trance':'', 'Comment':'飲み物のポスター', 'Type':'薄明の翼1話'},
  {'Id':'', 'Galar':'ROSH', 'Trance':'ROSE', 'Comment':'ローズのサイン', 'Type':'薄明の翼1話'},
  {'Id':'', 'Galar':'Ucidkaomhq', 'Trance':'', 'Comment':'赤い本', 'Type':'薄明の翼2話'},
  {'Id':'', 'Galar':'Nhgaidomrq', 'Trance':'', 'Comment':'緑の本', 'Type':'薄明の翼2話'},
  {'Id':'', 'Galar':'Aagolnhd iml croh Ugqnc', 'Trance':'', 'Comment':'緑の本サブタイトル', 'Type':'薄明の翼2話'},
  {'Id':'', 'Galar':'eqo', 'Trance':'', 'Comment':'水色のファイル', 'Type':'薄明の翼2話'},
  {'Id':'', 'Galar':'Haqkrhdakm', 'Trance':'', 'Comment':'青の本', 'Type':'薄明の翼2話'},
  {'Id':'', 'Galar':'Edi al', 'Trance':'', 'Comment':'青の本サブタイトル', 'Type':'薄明の翼2話'},
  {'Id':'', 'Galar':'Ofkcrnik', 'Trance':'', 'Comment':'ワンリキー\nチョコバー', 'Type':'薄明の翼2話'},
  {'Id':'', 'Galar':'Agfrlkolai', 'Trance':'', 'Comment':'ワンリキー\nチョコバー下段', 'Type':'薄明の翼2話'},
  {'Id':'', 'Galar':'SVFJU', 'Trance':'SAITO', 'Comment':'サイトウ 1段目', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'Haqkrhdakm', 'Trance':'', 'Comment':'サイトウ 2段目', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'TRNBOK VXDA', 'Trance':'', 'Comment':'サイトウ 3段目', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'DCVDB', 'Trance':'DANDE', 'Comment':'ダンデ 1段目', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'Nhgaidomrq', 'Trance':'', 'Comment':'ダンデ 2段目', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'Whqdglon', 'Trance':'', 'Comment':'ダンデ 3段目', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'GALAJ', 'Trance':'GALAR', 'Comment':'ガラル', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'RLDEJIM', 'Trance':'', 'Comment':'中央下', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'ZCISFHJBhLL', 'Trance':'MONSTER BALL', 'Comment':'モンスターボールのポスター', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'RE', 'Trance':'', 'Comment':'ポスターの右上', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'WeUTCEKV', 'Trance':'', 'Comment':'ブティック', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'lfd q lfd', 'Trance':'エイト o エイト', 'Comment':'きのみ屋', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'OoRq', 'Trance':'', 'Comment':'垂れ幕', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'EUT? DUeXE', 'Trance':'', 'Comment':'美容院', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'OoRq', 'Trance':'', 'Comment':'迷子札', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'CFSR VXDA', 'Trance':'', 'Comment':'迷子札\nハロン', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'FeeKU JVYU', 'Trance':'', 'Comment':'迷子札', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'EOU', 'Trance':'HOP', 'Comment':'迷子札\nホップ', 'Type':'薄明の翼3話'},
  {'Id':'', 'Galar':'Nhgaid Lorda', 'Trance':'', 'Comment':'エレベーター横の\n扉のプレート', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'ClkFkri', 'Trance':'', 'Comment':'雑誌1冊目のタイトル上', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Yrldcnoh', 'Trance':'', 'Comment':'雑誌1冊目のタイトル下', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Olqgki', 'Trance':'', 'Comment':'雑誌1冊目の左-上', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Clmkin', 'Trance':'', 'Comment':'雑誌1冊目の左-下', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Nqorngmq', 'Trance':'', 'Comment':'雑誌1冊目の右', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'MreJ', 'Trance':'', 'Comment':'雑誌2冊目のタイトル', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Hkcn', 'Trance':'', 'Comment':'雑誌2冊目の左上1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Fgok', 'Trance':'', 'Comment':'雑誌2冊目の左上2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'rifc', 'Trance':'', 'Comment':'雑誌2冊目の左上3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'agqn amo', 'Trance':'', 'Comment':'雑誌2冊目の左上4', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'qh Yig', 'Trance':'', 'Comment':'雑誌2冊目の左上5', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Wclr', 'Trance':'', 'Comment':'雑誌2冊目の細字', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Riqch Kdq', 'Trance':'', 'Comment':'雑誌2冊目の下の白字1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Dhkm eocd', 'Trance':'', 'Comment':'雑誌2冊目の下の白字2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'OMf', 'Trance':'', 'Comment':'雑誌の3冊目のタイトル', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'YINJEJ', 'Trance':'KIBANA', 'Comment':'雑誌の3冊目の左下-赤字', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Lgron', 'Trance':'', 'Comment':'雑誌の3冊目の左下-白字', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'WhlagdO', 'Trance':'', 'Comment':'雑誌の3冊目の左下-ピンク地', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'UVUK', 'Trance':'', 'Comment':'雑誌の3冊目の左下枠1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'klq fkacr', 'Trance':'', 'Comment':'雑誌の3冊目の左下枠2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Caqkol ik', 'Trance':'', 'Comment':'雑誌の3冊目の左下枠3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'danh aoqk', 'Trance':'', 'Comment':'雑誌の3冊目の左下枠4', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Khom', 'Trance':'', 'Comment':'雑誌の3冊目の左下枠外', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'k-q', 'Trance':'', 'Comment':'ダンデの映像 青枠\n初のハイフン', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'DCVDB', 'Trance':'DANDE', 'Comment':'ダンデの映像 「N」が異体字', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Riqch Kdq Dhkm', 'Trance':'', 'Comment':'ダンデの映像 赤枠', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Ofkcrnikdl', 'Trance':'', 'Comment':'ダンデの映像 左下', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'KSDEV iaLLl', 'Trance':'', 'Comment':'ヨシダ珈琲', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Wcl', 'Trance':'', 'Comment':'カメラ右上1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'OI', 'Trance':'', 'Comment':'カメラ右上2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Jnlm', 'Trance':'', 'Comment':'カメラ右上3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'oq_', 'Trance':'ISO', 'Comment':'カメラ下', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'oqg', 'Trance':'ISO', 'Comment':'カメラ下', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'OIVECX', 'Trance':'', 'Comment':'ソニアの研究所\nホワイトボード', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Bm', 'Trance':'', 'Comment':'左の書類', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'iq dcnoh Tk', 'Trance':'', 'Comment':'左の書類', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Ugmcd Wlmf ckiq', 'Trance':'', 'Comment':'左の書類', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Mlkqcdok', 'Trance':'', 'Comment':'左の書類', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Nmqfol Xhdk fcig', 'Trance':'', 'Comment':'左の書類', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Bkcno Jqc OrfkoS', 'Trance':'', 'Comment':'左の書類', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'DNoM', 'Trance':'', 'Comment':'左の書類 サインの枠', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'O', 'Trance':'', 'Comment':'左の書類 サイン', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'ROSH', 'Trance':'', 'Comment':'左の書類 サイン', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Khord', 'Trance':'', 'Comment':'右の書類 左上', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'UrkqdTraqaflk agc___', 'Trance':'', 'Comment':'右の書類 右上', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Nhgaidomrqeqoca', 'Trance':'', 'Comment':'右の書類 タイトル', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'IV', 'Trance':'', 'Comment':'右の書類 本文1-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'ECXeNKeSTKBLKUIe', 'Trance':'', 'Comment':'右の書類 本文1-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'IMFSFHLCRSEKBe', 'Trance':'', 'Comment':'右の書類 本文1-3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'ASKXBeSVHeR', 'Trance':'', 'Comment':'右の書類 本文2-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'akikmdalihak', 'Trance':'', 'Comment':'右の書類 本文2-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'OYFREHFLUNIHCAKFMVSLIeAHI', 'Trance':'', 'Comment':'右の書類 本文3-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'BgkrfUrkqdTraqaflk', 'Trance':'', 'Comment':'右の書類 本文3-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'BMSDAFIAKORAWSVEUK', 'Trance':'', 'Comment':'右の書類 本文4-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'LEXRE', 'Trance':'', 'Comment':'右の書類 本文4-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'eNqarko', 'Trance':'', 'Comment':'右の書類 本文4-3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'CAEFBReYITKRCLS', 'Trance':'', 'Comment':'右の書類 本文5-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'SNODWe', 'Trance':'', 'Comment':'右の書類 本文5-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'LMeJCkonrqlilanr', 'Trance':'', 'Comment':'右の書類 本文5-3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'cfdca', 'Trance':'', 'Comment':'右の書類 本文5-4', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Xcgkdlfokicrdral', 'Trance':'', 'Comment':'右の書類 本文6-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'onahdokqiaiakdaonlkagcaon', 'Trance':'', 'Comment':'右の書類 本文6-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Ronmlkqdh', 'Trance':'', 'Comment':'右の書類 本文7-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'grlkdcdk', 'Trance':'', 'Comment':'右の書類 本文7-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'ofkqhcaokolaicidkaom', 'Trance':'', 'Comment':'右の書類 本文7-3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Snoorkdaofmkd', 'Trance':'', 'Comment':'右の書類 本文8', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'M', 'Trance':'', 'Comment':'右の書類 本文', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Ucidk', 'Trance':'', 'Comment':'右の書類 下部 1-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'klq fkacr C__l ik', 'Trance':'', 'Comment':'右の書類 下部 1-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'danhaoqk VIY', 'Trance':'', 'Comment':'右の書類 下部 1-3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Aagolnhd iml Ugqn__', 'Trance':'', 'Comment':'右の書類 下部 1-4', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'aomhq', 'Trance':'', 'Comment':'右の書類 下部 2-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Lgron SKY__NCVIY', 'Trance':'', 'Comment':'右の書類 下部 2-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Edial Ur__ Sno', 'Trance':'', 'Comment':'右の書類 下部 2-3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Il mfakhia V__', 'Trance':'', 'Comment':'右の書類 下部 2-4', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'OfkcrnikdlH_hd_', 'Trance':'', 'Comment':'右の書類 下部 3-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'202003180346', 'Trance':'', 'Comment':'右の書類 下部 3-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'agfr_orn_f', 'Trance':'', 'Comment':'右の書類 下部 3-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'lriq rkiq__J__', 'Trance':'', 'Comment':'右の書類 下部 3-3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Mcno', 'Trance':'', 'Comment':'右の書類 下部 4-1', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'Riqch Kd__', 'Trance':'', 'Comment':'右の書類 下部 4-2', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'SKYhE UeNC__', 'Trance':'', 'Comment':'右の書類 下部 4-3', 'Type':'薄明の翼4話'},
  {'Id':'', 'Galar':'BMSDAFIAKORAWS', 'Trance':'', 'Comment':'ウィンドウ1,2,3,5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Daldhq', 'Trance':'', 'Comment':'ウィンドウ1,2,3,5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Ronmlkqdhgrlkd', 'Trance':'', 'Comment':'ウィンドウ1,2,5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Xcgkdlfokicrdr', 'Trance':'', 'Comment':'ウィンドウ1,5 2の赤文字', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Dfkcq', 'Trance':'', 'Comment':'ウィンドウ2', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Nhgaidomrq', 'Trance':'', 'Comment':'ウィンドウ2', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Haqkrhdakm', 'Trance':'', 'Comment':'ウィンドウ2', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Edial', 'Trance':'', 'Comment':'ウィンドウ2', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Srgcl', 'Trance':'', 'Comment':'ウィンドウ2,3,5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'CAEFBReYITKRCL', 'Trance':'', 'Comment':'ウィンドウ2,5の赤文字', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'ASKXBeSVHeRaki', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'OYFREHFLUNIHCA', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Edial', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Lgron', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Khord', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'qnmq', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Ricg', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'qnmq', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Xrk', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'gqadf', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'lmoanocd', 'Trance':'', 'Comment':'ウィンドウ5', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'MVKTO COENOE', 'Trance':'マクロコスモス', 'Comment':'', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Ronmlkqdhgrlkd', 'Trance':'', 'Comment':'ロトムの画面', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'ASKXB', 'Trance':'', 'Comment':'ロトムの画面', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Xcgkdlfokicrdr', 'Trance':'', 'Comment':'ロトムの画面', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'CAEFBReYITKRCL', 'Trance':'', 'Comment':'ロトムの画面', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Ucidkaomhq', 'Trance':'', 'Comment':'ロトムの画面', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'ASKXBeSVHeRaki', 'Trance':'', 'Comment':'ロトムの画面', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'OYFREHFLUNIHCA', 'Trance':'', 'Comment':'ロトムの画面', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Ofkcrnikdl', 'Trance':'', 'Comment':'ロトムの画面', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Agfrlkolai', 'Trance':'', 'Comment':'ロトムの画面', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Haqkrhdakm', 'Trance':'', 'Comment':'ロトムの画面 完了時', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Bgkrfaiak daonlkagcaonmrih', 'Trance':'', 'Comment':'ロトムの画面', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'MRCONA', 'Trance':'', 'Comment':'ビル名', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'Weaqhc', 'Trance':'', 'Comment':'ビル看板 上', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'mfkiqd', 'Trance':'', 'Comment':'ビル看板 中', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'OnlCIKE', 'Trance':'', 'Comment':'ビル看板 下', 'Type':'薄明の翼5話'},
  {'Id':'', 'Galar':'DNoM hqlJNo', 'Trance':'', 'Comment':'病室のポスター', 'Type':'薄明の翼6話'},
  {'Id':'', 'Galar':'Jq? OrfkoM', 'Trance':'', 'Comment':'病室のポスター', 'Type':'薄明の翼6話'},
  {'Id':'', 'Galar':'ELOF', 'Trance':'', 'Comment':'警備員室の扉のプレート', 'Type':'薄明の翼6話'},
  {'Id':'', 'Galar':'Si?', 'Trance':'', 'Comment':'飲み物のラベル', 'Type':'薄明の翼6話'},
  {'Id':'', 'Galar':'Dfkcq', 'Trance':'', 'Comment':'病室のポスター', 'Type':'薄明の翼6話'},
  {'Id':'', 'Galar':'BEKCVE', 'Trance':'REAGUE', 'Comment':'病室のポスター', 'Type':'薄明の翼6話'},
  {'Id':'', 'Galar':'GALAR', 'Trance':'GALAR', 'Comment':'病室のポスター', 'Type':'薄明の翼6話'},
  {'Id':'', 'Galar':'ank qh qchko', 'Trance':'', 'Comment':'通話画面', 'Type':'薄明の翼6話'},
  {'Id':'', 'Galar':'DCVDB', 'Trance':'ダンデ', 'Comment':'通話画面', 'Type':'薄明の翼6話'},
  {'Id':'', 'Galar':'oqg', 'Trance':'', 'Comment':'テロップ', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Ekgq hlmo Kdcglqrf', 'Trance':'', 'Comment':'テロップ', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'ROSH Kdq DCVDB qh', 'Trance':'', 'Comment':'テロップ', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Clmkin', 'Trance':'', 'Comment':'本のタイトル', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'eocd', 'Trance':'', 'Comment':'本のタイトル', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Traqaflk qchgo', 'Trance':'', 'Comment':'本のタイトル', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'KORHJ', 'Trance':'', 'Comment':'時計のブランド', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'FALE', 'Trance':'', 'Comment':'タクシー上', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'DCVDB', 'Trance':'', 'Comment':'新聞 見出し1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Daldhq', 'Trance':'', 'Comment':'新聞 見出し2', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'DNoM', 'Trance':'', 'Comment':'新聞 見出し2', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'ciohlo', 'Trance':'', 'Comment':'新聞 キバナ枠', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'WEJ', 'Trance':'', 'Comment':'新聞 本文1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'lri', 'Trance':'', 'Comment':'新聞 本文1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'CLe', 'Trance':'', 'Comment':'新聞 本文1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Sno', 'Trance':'', 'Comment':'新聞 本文1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Hkc lriq', 'Trance':'', 'Comment':'新聞 本文1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'AKIBKMAq', 'Trance':'', 'Comment':'新聞 本文1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Traqaflk', 'Trance':'', 'Comment':'新聞 本文1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'EcgVIYCe', 'Trance':'', 'Comment':'新聞 本文1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Ygciohlo', 'Trance':'', 'Comment':'新聞 本文1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'fr', 'Trance':'', 'Comment':'新聞 本文1', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Uci', 'Trance':'', 'Comment':'新聞 本文2', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Ihld', 'Trance':'', 'Comment':'新聞 本文2', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Fgok', 'Trance':'', 'Comment':'新聞 本文2', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'afr', 'Trance':'', 'Comment':'新聞 本文2', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'GM', 'Trance':'', 'Comment':'新聞 本文2', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'FALE', 'Trance':'', 'Comment':'新聞 本文2', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'ih', 'Trance':'', 'Comment':'新聞 本文2', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'afr Hl Yig', 'Trance':'', 'Comment':'新聞 見出し3', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'Kg crmfkiEc', 'Trance':'', 'Comment':'新聞 見出し3', 'Type':'薄明の翼7話'},
  {'Id':'', 'Galar':'USEHR', 'Trance':'', 'Comment':'カレンダー', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'nBledFJh', 'Trance':'', 'Comment':'カレンダー', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'KSHln', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'LMKR', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'BnedJ', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'TgCO', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'CV?T', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'D?C?', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'lr?h', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'earig Dqh', 'Trance':'', 'Comment':'ポスター左上1行目', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'ir aolmaf', 'Trance':'', 'Comment':'ポスター左上2行目', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'Lorda oqg', 'Trance':'', 'Comment':'ポスター左上3行目', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'Xh Rlq Kgcrmfki', 'Trance':'', 'Comment':'ポスター左下', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'SiN', 'Trance':'', 'Comment':'飲み物', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'ROafa', 'Trance':'', 'Comment':'道場の看板', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Ckon', 'Trance':'', 'Comment':'掛け軸', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Ucid', 'Trance':'', 'Comment':'掛け軸', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'IOWO', 'Trance':'HONO', 'Comment':'ほのおユニフォーム', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'FYWEROBBKI', 'Trance':'', 'Comment':'ガラル消防署', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'NYRVBY', 'Trance':'MAKUWA', 'Comment':'ファンレターの入った段ボール', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'OeeJ', 'Trance':'BEET', 'Comment':'バインダー 最上段', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'CEUUB OHeW', 'Trance':'', 'Comment':'バインダー1行目', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Alckalh EUTB', 'Trance':'', 'Comment':'バインダー2行目', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Rorofin', 'Trance':'', 'Comment':'バインダー3行目', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Bdfirg Vdrg', 'Trance':'', 'Comment':'バインダー4行目', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'VqdamonOeeW', 'Trance':'', 'Comment':'バインダー5行目', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Jfodiqk Efd', 'Trance':'', 'Comment':'バインダー6行目', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'KaqhdhgaJ', 'Trance':'', 'Comment':'バインダー7行目', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'JWE', 'Trance':'AKU', 'Comment':'あくユニフォーム', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Dhkmagfrm Ecg', 'Trance':'', 'Comment':'三闘の資料 タイトル', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Jl DciFkri', 'Trance':'', 'Comment':'三闘の資料 下部', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'OIVECX', 'Trance':'', 'Comment':'研究所のホワイトボード', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Agfrlk', 'Trance':'', 'Comment':'研究所のホワイトボード', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'DCVDB', 'Trance':'DANDE', 'Comment':'着信画面', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Aagolnhd ial croh Ugqnc', 'Trance':'', 'Comment':'電車内の電光掲示板', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'COXOn', 'Trance':'', 'Comment':'屋台（ピンク）', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'KAOD_', 'Trance':'', 'Comment':'屋台（赤）', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'JOOD', 'Trance':'FOOD', 'Comment':'屋台（オレンジ）', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'EKEKTEAZ', 'Trance':'', 'Comment':'屋台（青）', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'N', 'Trance':'', 'Comment':'屋台（緑）', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'KUTTh', 'Trance':'', 'Comment':'屋台（オレンジ）', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'AUXWEOY', 'Trance':'', 'Comment':'スポンサーのロゴ', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'ROSH', 'Trance':'ROSE', 'Comment':'マクロコスモスのロゴ', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'OeeJ', 'Trance':'BEET', 'Comment':'ビートのユニフォーム', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'DNOM', 'Trance':'', 'Comment':'師匠のユニフォーム', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'MVRY', 'Trance':'MARY', 'Comment':'マリィのユニフォーム', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'IKVqorNor', 'Trance':'', 'Comment':'スポンサーのロゴ', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Jfodiqk', 'Trance':'', 'Comment':'スポンサーのロゴ', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'SFAFIF OIE', 'Trance':'HIJIKI OKA', 'Comment':'スポンサーのロゴ', 'Type':'薄明の翼 EXPANSION'},
  {'Id':'', 'Galar':'Tafi', 'Trance':'', 'Comment':'スポンサーのロゴ', 'Type':'薄明の翼 EXPANSION'},

  // 鎧の孤島
  {'Id':'', 'Galar':'ABTBDIY', 'Trance':'', 'Comment':'改札上の看板', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Xcgkdlfok', 'Trance':'', 'Comment':'改札上電光掲示板 1段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'aom', 'Trance':'', 'Comment':'改札上電光掲示板 1段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'H aqkrhd', 'Trance':'', 'Comment':'改札上電光掲示板 1段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'aomh', 'Trance':'', 'Comment':'改札上電光掲示板 1段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'idomrqfok', 'Trance':'', 'Comment':'改札上電光掲示板 2段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'aomh', 'Trance':'', 'Comment':'改札上電光掲示板 2段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'H aqkrhd', 'Trance':'', 'Comment':'改札上電光掲示板 2段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'aomh', 'Trance':'', 'Comment':'改札上電光掲示板 2段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Nhga idomrqcidkaomhq', 'Trance':'', 'Comment':'改札上電光掲示板 3段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Nhgaidomrq', 'Trance':'', 'Comment':'改札上電光掲示板 3段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Rorofin', 'Trance':'', 'Comment':'駅内左電光掲示板左', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'15:04 Xcgkdlfok', 'Trance':'', 'Comment':'駅内左電光掲示板左', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Agfrl kol', 'Trance':'', 'Comment':'駅内左電光掲示板左', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ucidk: aonhqda', 'Trance':'', 'Comment':'駅内左電光掲示板左', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'H aqkrhdakm', 'Trance':'', 'Comment':'駅内左電光掲示板左', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ckonrql', 'Trance':'', 'Comment':'駅内左電光掲示板右', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'15:02 H aqkrhd', 'Trance':'', 'Comment':'駅内左電光掲示板右', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Vido mrq', 'Trance':'', 'Comment':'駅内左電光掲示板右', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ucidk: aomhqda', 'Trance':'', 'Comment':'駅内左電光掲示板右', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'rhdakmdakm', 'Trance':'', 'Comment':'駅内左電光掲示板右', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'CAEFBReYIT', 'Trance':'', 'Comment':'パンフレットスタンド', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'gkdlfokq', 'Trance':'', 'Comment':'パンフレットスタンド', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'ofkqh', 'Trance':'', 'Comment':'赤いパンフレット', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'GM', 'Trance':'', 'Comment':'アーマーガア交通', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'GM ABTBDIY', 'Trance':'', 'Comment':'ショップの黒い看板', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'BMSDAFIAK', 'Trance':'', 'Comment':'ショップ奥のプレート', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'CAEFBReY', 'Trance':'', 'Comment':'ショップ奥のパネル', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Rorofin', 'Trance':'', 'Comment':'ショップ奥のパネル', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'BRe', 'Trance':'', 'Comment':'ショップ奥のパネル 表', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'CL', 'Trance':'', 'Comment':'ショップ奥のパネル 表', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'DWeLM', 'Trance':'', 'Comment':'ショップ奥のパネル 表', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ckonrql', 'Trance':'', 'Comment':'ショップ奥のパネル 表1段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'crdral okqdh', 'Trance':'', 'Comment':'ショップ奥のパネル 表1段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ronmlkqd', 'Trance':'', 'Comment':'ショップ奥のパネル 表2段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'rlkdcdkodcdko', 'Trance':'', 'Comment':'ショップ奥のパネル 表2段目', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Roro', 'Trance':'', 'Comment':'券売機', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ronm lkqdh', 'Trance':'', 'Comment':'券売機', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'CAEFBR', 'Trance':'', 'Comment':'券売機の画面', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'OIVE', 'Trance':'', 'Comment':'駅外壁のプレート', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'DAFIAKO', 'Trance':'', 'Comment':'駅外壁のプレート', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'FLONDHCAKFM', 'Trance':'', 'Comment':'駅外壁のプレート', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'FI:AK', 'Trance':'', 'Comment':'駅外壁のプレート', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'DAFMAKOCAFI', 'Trance':'', 'Comment':'駅外壁のプレート', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'WAKI', 'Trance':'', 'Comment':'駅外壁のプレート', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'CAEFBMeNIT', 'Trance':'', 'Comment':'駅外壁のプレート', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'YBQeNST', 'Trance':'', 'Comment':'駅外壁のプレート', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'EFBRe', 'Trance':'', 'Comment':'駅外壁のプレート', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'ROafa', 'Trance':'', 'Comment':'マスター道場の看板', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'DNoM', 'Trance':'', 'Comment':'マスタードのジャケット', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'hqlJNo', 'Trance':'', 'Comment':'マスタードのジャケット', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ckon', 'Trance':'', 'Comment':'掛け軸（二人三脚）', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ucid', 'Trance':'', 'Comment':'掛け軸（和気藹々）', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Wclr', 'Trance':'', 'Comment':'掛け軸（余裕綽々）', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'YFRE', 'Trance':'', 'Comment':'額縁', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'SDAF', 'Trance':'', 'Comment':'額縁', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'MS', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Xcgk_', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ron_l', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Snoor', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Bgkrf', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Agfr', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ckonr_', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'CA', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Uci_k', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'e_oca', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'E_ial', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Khor', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Lgron', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Aagol', 'Trance':'', 'Comment':'木札額', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'BR', 'Trance':'', 'Comment':'道場内のマット', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'GALAJ BEKCVE', 'Trance':'GALAR REAGUE', 'Comment':'マスタードの部屋のポスター', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'ORAWSVEU', 'Trance':'', 'Comment':'マスタードの部屋のポスター', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'EFBRe YITKRC', 'Trance':'', 'Comment':'マスタードの部屋のお菓子の箱', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'OYFS', 'Trance':'', 'Comment':'マスタードの部屋のお菓子の袋', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'BMSDA', 'Trance':'', 'Comment':'ハイドの前のコルクボード', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'KRCLS', 'Trance':'', 'Comment':'ハイドの前のコルクボード', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Dfkcq', 'Trance':'', 'Comment':'段ボール', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ofkcrnik', 'Trance':'', 'Comment':'自動販売機', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Canr', 'Trance':'', 'Comment':'自販機のコイン投入口', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'BKSe', 'Trance':'MIZU', 'Comment':'みずの掛け軸', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'JWE', 'Trance':'AKU', 'Comment':'あくの掛け軸', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Lrlqc', 'Trance':'', 'Comment':'ディグダ探しお兄さんの看板', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'BLKUI', 'Trance':'', 'Comment':'ディグダ探しお兄さんの看板', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Ygciohlo', 'Trance':'', 'Comment':'ディグダ探しお兄さんの看板', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Lordaoqg', 'Trance':'', 'Comment':'ディグダ探しお兄さんの看板', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'eomkdJl', 'Trance':'', 'Comment':'ディグダ探しお兄さんの看板', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'Dhkm eo', 'Trance':'', 'Comment':'ディグダ探しお兄さんの看板', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'JNHV', 'Trance':'DOKU(毒)', 'Comment':'クララの服', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'OKUEUE', 'Trance':'', 'Comment':'クララの服', 'Type':'鎧の孤島'},
  {'Id':'', 'Galar':'FeeKU', 'Trance':'', 'Comment':'Tシャツ（フィールドちゃん）', 'Type':''},
  {'Id':'', 'Galar':'NKUU', 'Trance':'', 'Comment':'Tシャツ（ミッドくん）', 'Type':''},
  {'Id':'', 'Galar':'TCRAU', 'Trance':'', 'Comment':'Tシャツ（トラッドくん）', 'Type':''},
  {'Id':'', 'Galar':'JYU', 'Trance':'', 'Comment':'Tシャツ（ロンドくん）', 'Type':''},
  {'Id':'', 'Galar':'OANiSO', 'Trance':'', 'Comment':'Tシャツ（あらなみとあらぼり）', 'Type':''},
  {'Id':'', 'Galar':'hJieA', 'Trance':'', 'Comment':'服のメーカー', 'Type':''},
  {'Id':'', 'Galar':'VdYol', 'Trance':'', 'Comment':'Tシャツ（#7）', 'Type':''},
  {'Id':'', 'Galar':'OClT', 'Trance':'', 'Comment':'Tシャツ（#8）', 'Type':''},
  {'Id':'', 'Galar':'CJeN', 'Trance':'', 'Comment':'Tシャツ（#9）', 'Type':''},
  {'Id':'', 'Galar':'AKFMVS OYFREHL', 'Trance':'', 'Comment':'Tシャツ（ダイマックスバンド）', 'Type':''},
  {'Id':'', 'Galar':'RME', 'Trance':'', 'Comment':'Tシャツ（ダイマックスバンド）のロゴ', 'Type':''},
  {'Id':'', 'Galar':'Daldhq', 'Trance':'', 'Comment':'Tシャツ（こわいかお）', 'Type':''},
  {'Id':'', 'Galar':'DNoM hqLJNo VVadS', 'Trance':'', 'Comment':'Tシャツ（ナイトヘッド）', 'Type':''},
  {'Id':'', 'Galar':'DCVDB', 'Trance':'DANDE', 'Comment':'ホップの部屋のダンデのポスター', 'Type':''},
  {'Id':'', 'Galar':'SeeC chqllingi', 'Trance':'SEED challenge', 'Comment':'ホップの部屋のポスター', 'Type':''},
  {'Id':'', 'Galar':'VECXeNK', 'Trance':'', 'Comment':'リーグカードのデザイン', 'Type':''},
  {'Id':'', 'Galar':'REHFLU', 'Trance':'', 'Comment':'リーグカードのデザイン', 'Type':''},

  // 賞状
  {'Id':'', 'Galar':'XBeSVHeR', 'Trance':'', 'Comment':'賞状のとこ', 'Type':'賞状'},
  {'Id':'', 'Galar':'AKFMVSL', 'Trance':'', 'Comment':'プレイヤーのとこ', 'Type':'賞状'},
  {'Id':'', 'Galar':'EX', 'Trance':'', 'Comment':'下のとこ1', 'Type':'賞状'},
  {'Id':'', 'Galar':'BMSDAFIAK', 'Trance':'', 'Comment':'下のとこ2', 'Type':'賞状'},
  {'Id':'', 'Galar':'RAWSVEUKLEXRENCAE', 'Trance':'', 'Comment':'下のとこ3', 'Type':'賞状'},
  {'Id':'', 'Galar':'KITSNDAN', 'Trance':'', 'Comment':'下のとこ4', 'Type':'賞状'},
  {'Id':'', 'Galar':'FBReY', 'Trance':'', 'Comment':'下のとこ5', 'Type':'賞状'},
  {'Id':'', 'Galar':'KRCLS', 'Trance':'', 'Comment':'下のとこ6', 'Type':'賞状'},
  {'Id':'', 'Galar':'ODWeK', 'Trance':'', 'Comment':'下のとこ7', 'Type':'賞状'},
  {'Id':'', 'Galar':'XBeSVHeR', 'Trance':'', 'Comment':'ポケモン図鑑完成の賞状 賞状', 'Type':'賞状'},
  {'Id':'', 'Galar':'AKFMVSL', 'Trance':'', 'Comment':'ポケモン図鑑完成の賞状 プレイヤー', 'Type':'賞状'},
  {'Id':'', 'Galar':'EX BMSDAFIAK RAWSVEUKLEXRENCAE KITSNDAN', 'Trance':'', 'Comment':'ポケモン図鑑完成の賞状 賞状下部の文・上', 'Type':'賞状'},
  {'Id':'', 'Galar':'FBReY KRCLS ODWeK', 'Trance':'', 'Comment':'ポケモン図鑑完成の賞状 賞状下部の文・下', 'Type':'賞状'},
  {'Id':'', 'Galar':'GALAJ BEKCVE', 'Trance':'GALAR LEAGUE', 'Comment':'ポケモン図鑑完成の賞状 賞状左下の封蝋', 'Type':'賞状'},
  {'Id':'', 'Galar':'GVNE JREVM', 'Trance':'GAME FREAK', 'Comment':'ポケモン図鑑完成の賞状 賞状右下のロゴ', 'Type':'賞状'},
  {'Id':'', 'Galar':'XBeSVHeR', 'Trance':'', 'Comment':'ヨロイ島図鑑完成の賞状 賞状', 'Type':'賞状'},
  {'Id':'', 'Galar':'AKFMVSL', 'Trance':'', 'Comment':'ヨロイ島図鑑完成の賞状 プレイヤー', 'Type':'賞状'},
  {'Id':'', 'Galar':'EX BMSDAFIAK RAWSVEUKLEXRENCAE KITSNDAN', 'Trance':'', 'Comment':'ヨロイ島図鑑完成の賞状 賞状下部の文・上', 'Type':'賞状'},
  {'Id':'', 'Galar':'FBReY KRCLS ODWeK', 'Trance':'', 'Comment':'ヨロイ島図鑑完成の賞状 賞状下部の文・下', 'Type':'賞状'},
  {'Id':'', 'Galar':'GALAJ BEKCVE', 'Trance':'GALAR LEAGUE', 'Comment':'ヨロイ島図鑑完成の賞状 賞状左下の封蝋', 'Type':'賞状'},
  {'Id':'', 'Galar':'GVNE JREVM', 'Trance':'GAME FREAK', 'Comment':'ヨロイ島図鑑完成の賞状 賞状右下のロゴ', 'Type':'賞状'},
  {'Id':'', 'Galar':'XBeSVHeR', 'Trance':'', 'Comment':'カンムリ雪原図鑑完成の賞状 賞状', 'Type':'賞状'},
  {'Id':'', 'Galar':'AKFMVSL', 'Trance':'', 'Comment':'カンムリ雪原図鑑完成の賞状 プレイヤー', 'Type':'賞状'},
  {'Id':'', 'Galar':'EX BMSDAFIAK RAWSVEUKLEXRENCAE KITSNDAN', 'Trance':'', 'Comment':'カンムリ雪原図鑑完成の賞状 賞状下部の文・上', 'Type':'賞状'},
  {'Id':'', 'Galar':'FBReY KRCLS ODWeK', 'Trance':'', 'Comment':'カンムリ雪原図鑑完成の賞状 賞状下部の文・下', 'Type':'賞状'},
  {'Id':'', 'Galar':'GALAJ BEKCVE', 'Trance':'GALAR LEAGUE', 'Comment':'カンムリ雪原図鑑完成の賞状 賞状左下の封蝋', 'Type':'賞状'},
  {'Id':'', 'Galar':'GVNE JREVM', 'Trance':'GAME FREAK', 'Comment':'カンムリ雪原図鑑完成の賞状 賞状右下のロゴ', 'Type':'賞状'},

  // 会社名
  {'Id':'', 'Galar':'QCREIS', 'Trance':'POKJOB', 'Comment':'ポケジョブ', 'Type':'会社名'},
  {'Id':'', 'Galar':'MVKTO COENOE', 'Trance':'MACRO COSMOS', 'Comment':'マクロコスモス社 \nMとCが合わないのは語頭・語中形だからか \n会社名だから遊び心でもじったのか', 'Type':'会社名'},
  {'Id':'', 'Galar':'Rorofin', 'Trance':'Railway', 'Comment':'マクロコスモス・レールウェイズ \n赤色', 'Type':'会社名'},
  {'Id':'', 'Galar':'Kaqhdhga', 'Trance':'', 'Comment':'マクロコスモス・コンストラクション \n灰色', 'Type':'会社名'},
  {'Id':'', 'Galar':'Dofk', 'Trance':'Bank', 'Comment':'マクロコスモス・バンク \n緑色', 'Type':'会社名'},
  {'Id':'', 'Galar':'Jfodiqk', 'Trance':'', 'Comment':'マクロコスモス・\n黄色\n(英)MacroCosmosMedia', 'Type':'会社名'},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'マクロコスモス・テクノロジー \n黄緑色\n(英)MacroCosmosTech', 'Type':'会社名'},
  {'Id':'', 'Galar':'Tafi', 'Trance':'', 'Comment':'マクロコスモス・ライフ \nピンク', 'Type':'会社名'},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'マクロコスモス・エネルギー \nオレンジ', 'Type':'会社名'},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'マクロコスモス・エアラインズ \n青色', 'Type':'会社名'},
  {'Id':'', 'Galar':'MCR', 'Trance':'MCR', 'Comment':'MCR貨物', 'Type':'会社名'},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'マクロネット', 'Type':'会社名'},
  {'Id':'', 'Galar':'MC qtlhn', 'Trance':'', 'Comment':'MC証券', 'Type':'会社名'},
  {'Id':'', 'Galar':'MC rcuaf', 'Trance':'', 'Comment':'MC生命\nオニオンのジムのスポンサー', 'Type':'会社名'},
  {'Id':'', 'Galar':'Lgrdn fkacr', 'Trance':'', 'Comment':'ターフジムのスポンサー \nヒメンカの絵柄', 'Type':'会社名'},
  {'Id':'', 'Galar':'Mdrgqdif', 'Trance':'', 'Comment':'エンジンジムのスポンサー \nカブさんが描かれてる', 'Type':'会社名'},
  {'Id':'', 'Galar':'LIr', 'Trance':'', 'Comment':'エンジンジムのスポンサー \n上のポスターの左上にあった', 'Type':'会社名'},
  {'Id':'', 'Galar':'Clmkin', 'Trance':'', 'Comment':'アラベスクジムのスポンサー \n香水', 'Type':'会社名'},
  {'Id':'', 'Galar':'DMBRUX ITKCN', 'Trance':'', 'Comment':'ナックルジムのスポンサー \nプロテインみたいなやつ', 'Type':'会社名'},
  {'Id':'', 'Galar':'Ricg qnmq', 'Trance':'', 'Comment':'オニオンのジムのスポンサー \nカメラ/レドームシ', 'Type':'会社名'},
  {'Id':'', 'Galar':'Lmdt qW', 'Trance':'', 'Comment':'チャンピオンリーグ？のスポンサー', 'Type':'会社名'},
  {'Id':'', 'Galar':'IKVqorNor', 'Trance':'', 'Comment':'テレビマクロ\n(英)Macro Cosmos Television', 'Type':'会社名'},
  {'Id':'', 'Galar':'AUXWEOY', 'Trance':'', 'Comment':'チャンピオンリーグ？のスポンサー \nプーマみたいなやつ', 'Type':'会社名'},
  {'Id':'', 'Galar':'lfdqlfd', 'Trance':'エイト O エイト', 'Comment':'エイトオーエイト\nきのみショップ\n(英)Grow Sures', 'Type':'会社名'},
  {'Id':'', 'Galar':'WeUTCEKV', 'Trance':'BOUTIQUE(仏)', 'Comment':'ブティック(仏)', 'Type':'会社名'},
  {'Id':'', 'Galar':'BOEXIH YFF', 'Trance':'INN', 'Comment':'スボミーイン\n英Budew', 'Type':'会社名'},
  {'Id':'', 'Galar':'KSDEV iaLLl', 'Trance':'caffe(伊)', 'Comment':'ヨシダ珈琲', 'Type':'会社名'},
  {'Id':'', 'Galar':'Vdrthom Rcdor', 'Trance':'', 'Comment':'グラモフォンレコード', 'Type':'会社名'},
  {'Id':'', 'Galar':'Edial', 'Trance':'', 'Comment':'ガラル郵便\nポストの下の黒い文字', 'Type':'会社名'},
  {'Id':'', 'Galar':'Nhgaidomrq', 'Trance':'', 'Comment':'美容院', 'Type':'会社名'},
  {'Id':'', 'Galar':'OeeWNEER', 'Trance':'BOOKMAAK', 'Comment':'ブックマーク', 'Type':'会社名'},
  {'Id':'', 'Galar':'Ciko', 'Trance':'', 'Comment':'なみのり運輸\n(英)Surf Shipping', 'Type':'会社名'},
  {'Id':'', 'Galar':'AEUReY', 'Trance':'', 'Comment':'なみのり運輸\n下の文字', 'Type':'会社名'},
  {'Id':'', 'Galar':'Rrnh', 'Trance':'', 'Comment':'ラプラス造船\n(英)Lapras Shipwrights', 'Type':'会社名'},
  {'Id':'', 'Galar':'OEVSTIL', 'Trance':'', 'Comment':'ラプラス造船\n下の文字', 'Type':'会社名'},
  {'Id':'', 'Galar':'FYWEROBBKI', 'Trance':'', 'Comment':'ガラル消防署', 'Type':'会社名'},
  {'Id':'', 'Galar':'WeeFO WOin', 'Trance':'', 'Comment':'ドッコラー土木', 'Type':'会社名'},
  {'Id':'', 'Galar':'VUDF OWIN', 'Trance':'TURF FARM', 'Comment':'ターフ農園', 'Type':'会社名'},
  {'Id':'', 'Galar':'EHHLCCU OWS', 'Trance':'SEEFOOD BAR', 'Comment':'レストラン防波亭', 'Type':'会社名'},
  {'Id':'', 'Galar':'RoralAdci', 'Trance':'', 'Comment':'ホエルオー水産\n(英)Wailord Aquaculture', 'Type':'会社名'},
  {'Id':'', 'Galar':'SqH iqTTqR', 'Trance':'JET SETTER', 'Comment':'ジェットセッター', 'Type':'会社名'},
  {'Id':'', 'Galar':'Rod Aion', 'Trance':'', 'Comment':'ドント ブリスター', 'Type':'会社名'},
  {'Id':'', 'Galar':'ULCL', 'Trance':'フオグオ(仮名)', 'Comment':'レストラン フオグオ', 'Type':'会社名'},
  {'Id':'', 'Galar':'DFDDOBI', 'Trance':'', 'Comment':'ペリッパー便', 'Type':'会社名'},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'ボルチーニ', 'Type':'会社名'},
  {'Id':'', 'Galar':'OKBKeCOC', 'Trance':'', 'Comment':"ステーキハウス\n(英)Bob's Your Uncle", 'Type':'会社名'},
  {'Id':'', 'Galar':'Edial laidE', 'Trance':'Ιωνια(古希)', 'Comment':'ホテル イオニア', 'Type':'会社名'},
  {'Id':'', 'Galar':'GALAJ WNeY', 'Trance':'', 'Comment':'ガラル鉱産', 'Type':'会社名'},
  {'Id':'', 'Galar':'ILNESTA', 'Trance':'', 'Comment':'テレスクリーン', 'Type':'会社名'},
  {'Id':'', 'Galar':'Ricgqn Dfkaq', 'Trance':'', 'Comment':'シュートシティの広告 \nルリナのやつ', 'Type':'会社名'},
  {'Id':'', 'Galar':'OXVX M YCHHR', 'Trance':'', 'Comment':'(英)Mach Motors\n車のシンボル的なやつ', 'Type':'会社名'},
  {'Id':'', 'Galar':'Edial', 'Trance':'', 'Comment':'シュートシティの広告', 'Type':'会社名'},
  {'Id':'', 'Galar':'earig Dqh Edial', 'Trance':'', 'Comment':'シュートシティの広告\n上のと同じとこ', 'Type':'会社名'},
  {'Id':'', 'Galar':'Acdln Adoqnahln', 'Trance':'Daily Discavery', 'Comment':'デイリーディスカバリー\nウールーのやつ。服のメーカー', 'Type':'会社名'},
  {'Id':'', 'Galar':'Ogdqr', 'Trance':'', 'Comment':'シュートシティの広告\n眼鏡の広告\n(英)DEFOG', 'Type':'会社名'},
  {'Id':'', 'Galar':'Ucidkao', 'Trance':'', 'Comment':'シュートシティの広告', 'Type':'会社名'},
  {'Id':'', 'Galar':'Nmqol', 'Trance':'', 'Comment':'シュートシティの広告 \nホシガリス', 'Type':'会社名'},
  {'Id':'', 'Galar':'JCYU RONe', 'Trance':'', 'Comment':'ロンド ロゼ', 'Type':'会社名'},
  {'Id':'', 'Galar':'VEU', 'Trance':'', 'Comment':'シュートシティの駅広告\n電池？', 'Type':'会社名'},
  {'Id':'', 'Galar':'OKJI', 'Trance':'', 'Comment':'シュートシティの駅広告\n電池の右下\nKとIが逆向いてる......', 'Type':'会社名'},
  {'Id':'', 'Galar':'CAEF', 'Trance':'', 'Comment':'シュートシティの駅広告 \n歯', 'Type':'会社名'},
  {'Id':'', 'Galar':'DTUTOEF', 'Trance':'', 'Comment':'シュートモノレール', 'Type':'会社名'},
  {'Id':'', 'Galar':'CAEF', 'Trance':'', 'Comment':'シュートシティの駅広告 \nアイス', 'Type':'会社名'},
  {'Id':'', 'Galar':'BEFKUT SEVe', 'Trance':'', 'Comment':'ハガネール車両', 'Type':'会社名'},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'アウローラ', 'Type':'会社名'},
  {'Id':'', 'Galar':'SFAFWF OWE', 'Trance':'HIJIKI OKA', 'Comment':'ヒジキ オカ', 'Type':'会社名'},
  {'Id':'', 'Galar':'WSILYJWCRVe', 'Trance':'', 'Comment':'スパイク商工会', 'Type':'会社名'},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'イチバン', 'Type':'会社名'},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'ガラル警察署', 'Type':'会社名'},
  {'Id':'', 'Galar':'AJOS Lgroc', 'Trance':'YUME', 'Comment':'ゆめ牧場', 'Type':'会社名'},
  {'Id':'', 'Galar':'Nhgaidomrq', 'Trance':'', 'Comment':'シュートシティの広告', 'Type':'会社名'},
  {'Id':'', 'Galar':'GM', 'Trance':'', 'Comment':'ガラルタクシー', 'Type':'会社名'},
  {'Id':'', 'Galar':'eLM', 'Trance':'', 'Comment':'バンバドロ', 'Type':'会社名'},
  {'Id':'', 'Galar':'Vaoq Vldo', 'Trance':'', 'Comment':'服のメーカー', 'Type':'会社名'},
  {'Id':'', 'Galar':'ORAWS', 'Trance':'', 'Comment':'モノレール駅のケーキ？の広告', 'Type':'会社名'},
  {'Id':'', 'Galar':'FCYU Vkilr', 'Trance':'', 'Comment':'ロンドフラワーズ', 'Type':'会社名'},
  {'Id':'', 'Galar':'M U', 'Trance':'', 'Comment':'ナックルユニバーシティ', 'Type':'会社名'},
  {'Id':'', 'Galar':'WTESHUE ESFJCK', 'Trance':'', 'Comment':'アルセウス製薬\narceus', 'Type':'会社名'},
  {'Id':'', 'Galar':'Fmc', 'Trance':'', 'Comment':'ラス\n服のメーカー', 'Type':'会社名'},
  {'Id':'', 'Galar':'AUXWEOY', 'Trance':'', 'Comment':'デンソク\nプーマみたいなやつ', 'Type':'会社名'},
  {'Id':'', 'Galar':'VaoqVldo', 'Trance':'', 'Comment':'キルクスジムのスポンサー', 'Type':'会社名'},
  {'Id':'', 'Galar':'Ofkcrn ikdl', 'Trance':'', 'Comment':'バウジムのスポンサー', 'Type':'会社名'},
  {'Id':'', 'Galar':'hJieA', 'Trance':'', 'Comment':'(英)Celebrity\nダイヤみたいなロゴ', 'Type':'会社名'},
  {'Id':'', 'Galar':'Ofkcrn ikdl', 'Trance':'', 'Comment':'バウジムのスポンサー\nおいしい水', 'Type':'会社名'},
  {'Id':'', 'Galar':'Agfrlk', 'Trance':'', 'Comment':'キルクスジムのスポンサー', 'Type':'会社名'},

  // その他
  {'Id':'', 'Galar':'SNODWeLMeJ', 'Trance':'', 'Comment':'エンジンシティのポスター \n キョダイマックスリザードン\n１行目', 'Type':''},
  {'Id':'', 'Galar':'LEXREeN', 'Trance':'', 'Comment':'エンジンシティのポスター \n２行目', 'Type':''},
  {'Id':'', 'Galar':'AKORAW', 'Trance':'', 'Comment':'エンジンシティのポスター \n２行目', 'Type':''},
  {'Id':'', 'Galar':'SVEUK', 'Trance':'', 'Comment':'エンジンシティのポスター \n３行目', 'Type':''},
  {'Id':'', 'Galar':'BMSDAFI', 'Trance':'', 'Comment':'エンジンシティのポスター \n３行目', 'Type':''},
  {'Id':'', 'Galar':'CAEFBReYITKRCLS', 'Trance':'', 'Comment':'エンジンシティのポスター \n４行目', 'Type':''},
  {'Id':'', 'Galar':'Xh', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕1', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'Rlq', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕2', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'Kgcrmfki', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕3', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'Ecg', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕4', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'Clk', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕5', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'Vm', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕6', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'Clmkin', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕7', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'qgd', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕7', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'ilorg', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕9', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'OYFREH', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕 footer1', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'FLUNI', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕 footer2', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'HCAKFMVSLIeA', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕 footer3', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'HI', 'Trance':'', 'Comment':'ガラルリーグの垂れ幕 footer4', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'Mrkcg', 'Trance':'', 'Comment':'英雄の湯 タイトル1', 'Type':''},
  {'Id':'', 'Galar':'Vlohlmn', 'Trance':'', 'Comment':'英雄の湯 タイトル2', 'Type':''},
  {'Id':'', 'Galar':'Srgcl', 'Trance':'', 'Comment':'英雄の湯 本文1', 'Type':''},
  {'Id':'', 'Galar':'ohd', 'Trance':'', 'Comment':'英雄の湯 本文2', 'Type':''},
  {'Id':'', 'Galar':'Ugmcd', 'Trance':'', 'Comment':'英雄の湯 本文3', 'Type':''},
  {'Id':'', 'Galar':'Wlmf', 'Trance':'', 'Comment':'英雄の湯 本文4', 'Type':''},
  {'Id':'', 'Galar':'ckiq', 'Trance':'', 'Comment':'英雄の湯 本文5', 'Type':''},
  {'Id':'', 'Galar':'gio', 'Trance':'', 'Comment':'英雄の湯 本文6', 'Type':''},
  {'Id':'', 'Galar':'Lgron', 'Trance':'', 'Comment':'英雄の湯 本文7', 'Type':''},
  {'Id':'', 'Galar':'Urkqd', 'Trance':'', 'Comment':'英雄の湯 本文8', 'Type':''},
  {'Id':'', 'Galar':'Sno', 'Trance':'', 'Comment':'英雄の湯 本文9', 'Type':''},
  {'Id':'', 'Galar':'Traqaflk', 'Trance':'', 'Comment':'英雄の湯 本文10', 'Type':''},
  {'Id':'', 'Galar':'Ygciohlo', 'Trance':'', 'Comment':'英雄の湯 本文11', 'Type':''},
  {'Id':'', 'Galar':'Vm', 'Trance':'', 'Comment':'英雄の湯 本文12', 'Type':''},
  {'Id':'', 'Galar':'Clmkin', 'Trance':'', 'Comment':'英雄の湯 本文13', 'Type':''},
  {'Id':'', 'Galar':'qgd', 'Trance':'', 'Comment':'英雄の湯 本文14', 'Type':''},
  {'Id':'', 'Galar':'ilorg', 'Trance':'', 'Comment':'英雄の湯 本文15', 'Type':''},
  {'Id':'', 'Galar':'Mlkqcdok', 'Trance':'', 'Comment':'英雄の湯 本文16', 'Type':''},
  {'Id':'', 'Galar':'Edial', 'Trance':'', 'Comment':'英雄の湯 本文17', 'Type':''},
  {'Id':'', 'Galar':'Vm', 'Trance':'', 'Comment':'ステーキハウスの賞状1', 'Type':''},
  {'Id':'', 'Galar':'Clmkin', 'Trance':'', 'Comment':'ステーキハウスの賞状2', 'Type':''},
  {'Id':'', 'Galar':'qgd', 'Trance':'', 'Comment':'ステーキハウスの賞状3', 'Type':''},
  {'Id':'', 'Galar':'ilorg', 'Trance':'', 'Comment':'ステーキハウスの賞状4', 'Type':''},
  {'Id':'', 'Galar':'Mlkqcdok', 'Trance':'', 'Comment':'ステーキハウスの賞状5', 'Type':''},
  {'Id':'', 'Galar':'Aq', 'Trance':'', 'Comment':'ステーキハウスの賞状6', 'Type':''},
  {'Id':'', 'Galar':'Nmqfol', 'Trance':'', 'Comment':'ステーキハウスの賞状7', 'Type':''},
  {'Id':'', 'Galar':'Xhdk', 'Trance':'', 'Comment':'ステーキハウスの賞状8', 'Type':''},
  {'Id':'', 'Galar':'fcig', 'Trance':'', 'Comment':'ステーキハウスの賞状9', 'Type':''},
  {'Id':'', 'Galar':'Kl', 'Trance':'', 'Comment':'ステーキハウスの賞状10', 'Type':''},
  {'Id':'', 'Galar':'Il', 'Trance':'', 'Comment':'シュートジムの地下控え室のモニター1\nどこが始まりか分からない', 'Type':''},
  {'Id':'', 'Galar':'mfakhia', 'Trance':'', 'Comment':'シュートジムの地下控え室のモニター2', 'Type':''},
  {'Id':'', 'Galar':'Vgr', 'Trance':'', 'Comment':'シュートジムの地下控え室のモニター3', 'Type':''},
  {'Id':'', 'Galar':'agfrm', 'Trance':'', 'Comment':'シュートジムの地下控え室のモニター4', 'Type':''},
  {'Id':'', 'Galar':'NqorngmqIl', 'Trance':'', 'Comment':'シュートジムの地下控え室のモニター5', 'Type':''},
  {'Id':'', 'Galar':'mfakhia', 'Trance':'', 'Comment':'シュートジムの地下控え室のモニター6', 'Type':''},
  {'Id':'', 'Galar':'Vgr', 'Trance':'', 'Comment':'シュートジムの地下控え室のモニター7', 'Type':''},
  {'Id':'', 'Galar':'agfrm', 'Trance':'', 'Comment':'シュートジムの地下控え室のモニター8', 'Type':''},
  {'Id':'', 'Galar':'Il', 'Trance':'', 'Comment':'ニュース記事\nサイトタイトル？1', 'Type':''},
  {'Id':'', 'Galar':'mfakh', 'Trance':'', 'Comment':'ニュース記事\nサイトタイトル？2', 'Type':''},
  {'Id':'', 'Galar':'Ckonrq', 'Trance':'', 'Comment':'ニュース記事\nニュースタイトル？1', 'Type':''},
  {'Id':'', 'Galar':'DCVDB', 'Trance':'', 'Comment':'ニュース記事\nニュースタイトル？2', 'Type':''},
  {'Id':'', 'Galar':'fdcamr', 'Trance':'', 'Comment':'ニュース記事\nニュースタイトル？3', 'Type':''},
  {'Id':'', 'Galar':'rifcag', 'Trance':'', 'Comment':'ニュース記事\nサブタイトル', 'Type':''},
  {'Id':'', 'Galar':'Ckonrql', 'Trance':'', 'Comment':'ニュース記事\n本文1', 'Type':''},
  {'Id':'', 'Galar':'Ronmlkqdhnrcfdc', 'Trance':'', 'Comment':'ニュース記事\n本文2', 'Type':''},
  {'Id':'', 'Galar':'ilan', 'Trance':'', 'Comment':'ニュース記事\n本文3', 'Type':''},
  {'Id':'', 'Galar':'rcfdc', 'Trance':'', 'Comment':'ニュース記事\n本文4', 'Type':''},
  {'Id':'', 'Galar':'amrlqarko', 'Trance':'', 'Comment':'ニュース記事\n本文5', 'Type':''},
  {'Id':'', 'Galar':'Snoorkork', 'Trance':'', 'Comment':'ニュース記事\n本文6', 'Type':''},
  {'Id':'', 'Galar':'dao', 'Trance':'', 'Comment':'ニュース記事\n本文7', 'Type':''},
  {'Id':'', 'Galar':'Bgkrf', 'Trance':'', 'Comment':'ニュース記事\n本文8', 'Type':''},
  {'Id':'', 'Galar':'grlkdcdlofkqhcao', 'Trance':'', 'Comment':'ニュース記事\n本文9', 'Type':''},
  {'Id':'', 'Galar':'fmkdak', 'Trance':'', 'Comment':'ニュース記事\n本文10', 'Type':''},
  {'Id':'', 'Galar':'ihakhak', 'Trance':'', 'Comment':'ニュース記事\n本文11', 'Type':''},
  {'Id':'', 'Galar':'RLDEIM', 'Trance':'', 'Comment':'スタジアム \nSTADIUMだと文字数合わない', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'SeeC chllingi', 'Trance':'SEED challenge', 'Comment':'スタジアムのメインモニター', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'REYFBE OIVECX', 'Trance':'REAGUE ~~', 'Comment':'スタジアムのメインモニター', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'Whtdglon DVJ', 'Trance':'Champion CUP', 'Comment':'チャンピオンリーグ中の垂れ幕 \nポスター', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'AFIA TKRC', 'Trance':'', 'Comment':'スタジアムの左通用口', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'WSV TKRC', 'Trance':'', 'Comment':'スタジアムの右通用口', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'Nhgaid Lorda', 'Trance':'', 'Comment':'更衣室', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'CYDAMUQTYXR', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n左下', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'noork', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n一番上', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'IJRQTYX', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n左１行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'HLeV', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n左２行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'DAMUQT', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n左３行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'XRMUQT', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n左４行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'HLeVIYXR', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n左５行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'AMUQTW', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n真ん中１行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'BSKHLeVI', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n真ん中２行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'OFEDAN', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n真ん中３行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'BSKHL', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n真ん中４行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'OFEDAMU', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n真ん中５行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'OFEDANV', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n右1行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'JCYXRBSK', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n右2行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'CYDAMUQT', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n右3行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'NVIJC', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n右4行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'eNVIJ', 'Trance':'', 'Comment':'エンジンスタジアムの構内図 \n右5行目', 'Type':'スタジアム'},
  {'Id':'', 'Galar':'BMSDAFI', 'Trance':'', 'Comment':'スタジアム前の立て看板1', 'Type':''},
  {'Id':'', 'Galar':'AKORAW', 'Trance':'', 'Comment':'スタジアム前の立て看板2', 'Type':''},
  {'Id':'', 'Galar':'SVEUK', 'Trance':'', 'Comment':'スタジアム前の立て看板3', 'Type':''},
  {'Id':'', 'Galar':'LEXREeN', 'Trance':'', 'Comment':'スタジアム前の立て看板4', 'Type':''},
  {'Id':'', 'Galar':'REYF', 'Trance':'', 'Comment':'シュートジム内左の赤いポスター1', 'Type':''},
  {'Id':'', 'Galar':'Aagolnhd', 'Trance':'', 'Comment':'シュートジム内左の赤いポスター2', 'Type':''},
  {'Id':'', 'Galar':'imlcroh', 'Trance':'', 'Comment':'シュートジム内左の赤いポスター3', 'Type':''},
  {'Id':'', 'Galar':'Ugqnc', 'Trance':'', 'Comment':'シュートジム内左の赤いポスター4', 'Type':''},
  {'Id':'', 'Galar':'Lgro', 'Trance':'', 'Comment':'シュートジム内左の赤いポスター5', 'Type':''},
  {'Id':'', 'Galar':'IMFSF', 'Trance':'', 'Comment':'シュートジム内左の青いポスター1', 'Type':''},
  {'Id':'', 'Galar':'klq fkacr', 'Trance':'', 'Comment':'シュートジム内左の青いポスター2', 'Type':''},
  {'Id':'', 'Galar':'Caqkol ik', 'Trance':'', 'Comment':'シュートジム内左の青いポスター3', 'Type':''},
  {'Id':'', 'Galar':'danhaoqk', 'Trance':'', 'Comment':'シュートジム内左の青いポスター4', 'Type':''},
  {'Id':'', 'Galar':'Vlohlmn', 'Trance':'', 'Comment':'シュートジム内左の青いポスター5', 'Type':''},
  {'Id':'', 'Galar':'HLCRS', 'Trance':'', 'Comment':'シュートジムのモニター\nゴリランダー1', 'Type':''},
  {'Id':'', 'Galar':'Ihld', 'Trance':'', 'Comment':'シュートジムのモニター\nゴリランダー2', 'Type':''},
  {'Id':'', 'Galar':'EKBeAS', 'Trance':'', 'Comment':'シュートジムのモニター\nニャース1', 'Type':''},
  {'Id':'', 'Galar':'Bm', 'Trance':'', 'Comment':'シュートジムのモニター\nニャース2', 'Type':''},
  {'Id':'', 'Galar':'DWeLMeJ', 'Trance':'', 'Comment':'シュートジムのモニター\nインテレオン1', 'Type':''},
  {'Id':'', 'Galar':'Urkqd', 'Trance':'', 'Comment':'シュートジムのモニター\nインテレオン2', 'Type':''},
  {'Id':'', 'Galar':'CLSSNO', 'Trance':'', 'Comment':'シュートジムのモニター\nエースバーン1', 'Type':''},
  {'Id':'', 'Galar':'Traqaflk', 'Trance':'', 'Comment':'シュートジムのモニター\nエースバーン2', 'Type':''},
  {'Id':'', 'Galar':'eYITKR', 'Trance':'', 'Comment':'シュートジムのモニター\nパルスワン1', 'Type':''},
  {'Id':'', 'Galar':'Ygci', 'Trance':'', 'Comment':'シュートジムのモニター\nパルスワン2', 'Type':''},
  {'Id':'', 'Galar':'Xrkg', 'Trance':'', 'Comment':'エンジンジムの得点ボード1', 'Type':''},
  {'Id':'', 'Galar':'danh', 'Trance':'', 'Comment':'エンジンジムの得点ボード2', 'Type':''},
  {'Id':'', 'Galar':'kol', 'Trance':'', 'Comment':'エンジンジムの得点ボード3', 'Type':''},
  {'Id':'', 'Galar':'Caq', 'Trance':'', 'Comment':'エンジンジムの得点ボード4', 'Type':''},
  {'Id':'', 'Galar':'qadf', 'Trance':'', 'Comment':'エンジンジムの得点ボード5', 'Type':''},
  {'Id':'', 'Galar':'Caqko', 'Trance':'', 'Comment':'スタジアムの非常灯？', 'Type':''},
  {'Id':'', 'Galar':'AKIBKM', 'Trance':'', 'Comment':'ダイマックスした時', 'Type':''},
  {'Id':'', 'Galar':'CLeY', 'Trance':'', 'Comment':'最後のポケモンを倒したとき', 'Type':''},
  {'Id':'', 'Galar':'VIYCe', 'Trance':'', 'Comment':'戦闘中', 'Type':''},
  {'Id':'', 'Galar':'ABTBDIY', 'Trance':'STATION', 'Comment':'小型駅構内の青い看板', 'Type':'その他'},
  {'Id':'', 'Galar':'BMSDAFIAK', 'Trance':'', 'Comment':'小型駅のカウンターの奥のプレート', 'Type':'その他'},
  {'Id':'', 'Galar':'CAEFBReY', 'Trance':'', 'Comment':'小型駅のカウンターの奥の貼り紙1段目', 'Type':'その他'},
  {'Id':'', 'Galar':'Rorofin', 'Trance':'Railway', 'Comment':'小型駅のカウンターの奥の貼り紙2段目', 'Type':'その他'},
  {'Id':'', 'Galar':'BRe', 'Trance':'', 'Comment':'小型駅のカウンターの奥の貼り紙 \n表の左上、時間のことか', 'Type':'その他'},
  {'Id':'', 'Galar':'CL', 'Trance':'', 'Comment':'小型駅のカウンターの奥の貼り紙 \n表の真ん中', 'Type':'その他'},
  {'Id':'', 'Galar':'DWeLM', 'Trance':'', 'Comment':'小型駅のカウンターの奥の貼り紙 \n表の右上', 'Type':'その他'},
  {'Id':'', 'Galar':'OIVE', 'Trance':'', 'Comment':'小型駅の外のプレート', 'Type':'その他'},
  {'Id':'', 'Galar':'CAEFBReYIT', 'Trance':'', 'Comment':'全駅のパンフレットスタンド', 'Type':'その他'},
  {'Id':'', 'Galar':'gkdlfoki', 'Trance':'', 'Comment':'全駅のパンフスタンド', 'Type':'その他'},
  {'Id':'', 'Galar':'ofkqh', 'Trance':'', 'Comment':'全駅のパンフスタンド\n赤い冊子', 'Type':'その他'},
  {'Id':'', 'Galar':'Xcgkdlfok', 'Trance':'', 'Comment':'駅のポスター右 \nエンディング後', 'Type':'その他'},
  {'Id':'', 'Galar':'CEUUB', 'Trance':'', 'Comment':'駅のポスター左 \nエンディング後', 'Type':'その他'},
  {'Id':'', 'Galar':'Xcgkdlfok aom', 'Trance':'', 'Comment':'全駅 改札上の電光掲示板 左上 \nアラビア数字が使われている', 'Type':'その他'},
  {'Id':'', 'Galar':'idomrqfok aomh', 'Trance':'', 'Comment':'全駅 改札上の電光掲示板 左下', 'Type':'その他'},
  {'Id':'', 'Galar':'H aqkrhd aomh', 'Trance':'', 'Comment':'全駅 改札上の電光掲示板', 'Type':'その他'},
  {'Id':'', 'Galar':'Nhga idomrq', 'Trance':'', 'Comment':'全駅 改札上の電光掲示板 下の黄色文字', 'Type':'その他'},
  {'Id':'', 'Galar':'cidkaomhq', 'Trance':'', 'Comment':'全駅 改札上の電光掲示板 下の文字', 'Type':'その他'},
  {'Id':'', 'Galar':'UcidkaomhqUci', 'Trance':'', 'Comment':'大型駅のフードコート', 'Type':''},
  {'Id':'', 'Galar':'GALAJ BEKCVE', 'Trance':'GALAR REAGUE', 'Comment':'大型駅のサービスカウンター', 'Type':''},
  {'Id':'', 'Galar':'Mdrgqdi', 'Trance':'', 'Comment':'大型駅の観光案内所？\niが半分切れてる', 'Type':''},
  {'Id':'', 'Galar':'Xhdk', 'Trance':'', 'Comment':'大型駅の観光案内所？\n青いプレート1', 'Type':''},
  {'Id':'', 'Galar':'fcig', 'Trance':'', 'Comment':'大型駅の観光案内所？\n青いプレート2', 'Type':''},
  {'Id':'', 'Galar':'BFRHIAVB', 'Trance':'', 'Comment':'大型駅のフレンドリィショップ1', 'Type':''},
  {'Id':'', 'Galar':'OKBKeCOC', 'Trance':'', 'Comment':'大型駅のフレンドリィショップ2', 'Type':''},
  {'Id':'', 'Galar':'ifcagqn amoqh', 'Trance':'', 'Comment':'大型駅 改札の上のプレート', 'Type':''},
  {'Id':'', 'Galar':'Clmkin qgd ilorg', 'Trance':'', 'Comment':'大型駅 改札上のポスター \nモンスターボールのやつ', 'Type':''},
  {'Id':'', 'Galar':'Ronm lkqdh', 'Trance':'', 'Comment':'全駅 黄色の券売機', 'Type':''},
  {'Id':'', 'Galar':'CAETBR', 'Trance':'', 'Comment':'全駅 黄色の券売機のディスプレイ', 'Type':''},
  {'Id':'', 'Galar':'NBIHTOFI', 'Trance':'', 'Comment':'大型駅のソファー', 'Type':''},
  {'Id':'', 'Galar':'Rorohin', 'Trance':'Railway', 'Comment':'小型駅の電光掲示板 左1行目', 'Type':'その他'},
  {'Id':'', 'Galar':'Xcgkdlfok', 'Trance':'', 'Comment':'小型駅の電光掲示板 左2行目', 'Type':''},
  {'Id':'', 'Galar':'Agfrl kol', 'Trance':'', 'Comment':'小型駅の電光掲示板 左3行目', 'Type':''},
  {'Id':'', 'Galar':'Ucidk', 'Trance':'', 'Comment':'小型駅の電光掲示板 左4行目左', 'Type':''},
  {'Id':'', 'Galar':'aomhqda', 'Trance':'', 'Comment':'小型駅の電光掲示板 左4行目右', 'Type':''},
  {'Id':'', 'Galar':'Haqkrhdakm', 'Trance':'', 'Comment':'小型駅の電光掲示板 左5行目', 'Type':''},
  {'Id':'', 'Galar':'Ckonrql', 'Trance':'', 'Comment':'小型駅の電光掲示板 右1行目', 'Type':''},
  {'Id':'', 'Galar':'Haqkrhd', 'Trance':'', 'Comment':'小型駅の電光掲示板 右2行目', 'Type':''},
  {'Id':'', 'Galar':'Vido mrq', 'Trance':'', 'Comment':'小型駅の電光掲示板 右3行目', 'Type':''},
  {'Id':'', 'Galar':'Ucidk', 'Trance':'', 'Comment':'小型駅の電光掲示板 右4行目左', 'Type':''},
  {'Id':'', 'Galar':'aomhqda', 'Trance':'', 'Comment':'小型駅の電光掲示板 右4行目右', 'Type':''},
  {'Id':'', 'Galar':'rhdakmdakm', 'Trance':'', 'Comment':'小型駅の電光掲示板 右5行目', 'Type':''},
  {'Id':'', 'Galar':'EKBeASKX', 'Trance':'', 'Comment':'シュートモノレールのエレベーター', 'Type':''},
  {'Id':'', 'Galar':'Agfrlkolai', 'Trance':'', 'Comment':'シュートモノレールのエレベーター\nモノレール駅構内', 'Type':''},
  {'Id':'', 'Galar':'SKXBeS', 'Trance':'', 'Comment':'モノレール駅の立入禁止の扉', 'Type':''},
  {'Id':'', 'Galar':'qorNorhH?I', 'Trance':'', 'Comment':'モノレール駅の右手前のカウンター\nの上のパンフレット', 'Type':''},
  {'Id':'', 'Galar':'Vdrghom', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの前の立て看板1', 'Type':''},
  {'Id':'', 'Galar':'Rcdor', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの前の立て看板2', 'Type':''},
  {'Id':'', 'Galar':'BFTHIAVB', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの前の立て看板3', 'Type':''},
  {'Id':'', 'Galar':'DAFIAKO', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの黒丸のポスター', 'Type':''},
  {'Id':'', 'Galar':'DWeLMeJ', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nのポスター', 'Type':''},
  {'Id':'', 'Galar':'TKB', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの商品1', 'Type':''},
  {'Id':'', 'Galar':'IMFSFHLC', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの商品2', 'Type':''},
  {'Id':'', 'Galar':'OYFS', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの商品3', 'Type':''},
  {'Id':'', 'Galar':'VEUK', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの商品4', 'Type':''},
  {'Id':'', 'Galar':'OIVE\nEC', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの商品5', 'Type':''},
  {'Id':'', 'Galar':'COC\nROOI', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの商品6', 'Type':''},
  {'Id':'', 'Galar':'REYFB', 'Trance':'', 'Comment':'モノレール駅のフレンドリィショップ\nの商品7', 'Type':''},
  {'Id':'', 'Galar':'Yrl mkdrn', 'Trance':'', 'Comment':'モノレール駅にある案内板↑', 'Type':''},
  {'Id':'', 'Galar':'Xh Rlq', 'Trance':'', 'Comment':'モノレール駅にある案内板↑', 'Type':''},
  {'Id':'', 'Galar':'Kgcrmfki', 'Trance':'', 'Comment':'モノレール駅にある案内板↗', 'Type':''},
  {'Id':'', 'Galar':'Ldr Bkcno', 'Trance':'', 'Comment':'モノレール駅にある案内板→', 'Type':''},
  {'Id':'', 'Galar':'Xhdk fcig', 'Trance':'', 'Comment':'モノレール駅にある案内板↓', 'Type':''},
  {'Id':'', 'Galar':'Srgcl ohd Ugmcd', 'Trance':'', 'Comment':'モノレール駅にある案内板6', 'Type':''},
  {'Id':'', 'Galar':'hlno', 'Trance':'', 'Comment':'モノレール乗り場の看板', 'Type':''},
  {'Id':'', 'Galar':'IMFSFHLCRSEKBeASKXBeSVHeR', 'Trance':'', 'Comment':'モノレール駅\nモノレールのポスター', 'Type':''},
  {'Id':'', 'Galar':'Snoorkdaofmkdakik', 'Trance':'', 'Comment':'モノレール駅\nモンボケーキのポスター', 'Type':''},
  {'Id':'', 'Galar':'ORAWS', 'Trance':'', 'Comment':'モノレール駅\nモンボケーキのポスター2', 'Type':''},
  {'Id':'', 'Galar':'OIVE', 'Trance':'', 'Comment':'ワイルドエリア駅\n外のプレート1', 'Type':''},
  {'Id':'', 'Galar':'DAFIAKO', 'Trance':'', 'Comment':'ワイルドエリア駅\n外のプレート2', 'Type':''},
  {'Id':'', 'Galar':'KFLONDICVKF', 'Trance':'', 'Comment':'ワイルドエリア駅\n外のプレート3', 'Type':''},
  {'Id':'', 'Galar':'FIAK', 'Trance':'', 'Comment':'ワイルドエリア駅\n外のプレート4', 'Type':''},
  {'Id':'', 'Galar':'GVNE JREVM', 'Trance':'GAME FREAK', 'Comment':'ゲームフリーク', 'Type':'固有名詞'},
  {'Id':'', 'Galar':'RoM TQIiHrk', 'Trance':'NoW LOAdIng', 'Comment':'ロード中 \n大文字と小文字が混ざってる', 'Type':'その他'},
  {'Id':'', 'Galar':'Ghman', 'Trance':'Galar', 'Comment':'ガラル \nチャンネル名', 'Type':'その他'},
  {'Id':'', 'Galar':'Dcalld', 'Trance':'', 'Comment':' \nチャンネル名', 'Type':'その他'},
  {'Id':'', 'Galar':'Xahiomc', 'Trance':'', 'Comment':' \nチャンネル名', 'Type':'その他'},
  {'Id':'', 'Galar':'Ckiaac', 'Trance':'', 'Comment':' \n動画タイトル', 'Type':'その他'},
  {'Id':'', 'Galar':'Rgaqk', 'Trance':'', 'Comment':' \n動画タイトル', 'Type':'その他'},
  {'Id':'', 'Galar':'Adhq', 'Trance':'', 'Comment':' \n動画タイトル', 'Type':'その他'},
  {'Id':'', 'Galar':'Rhgq', 'Trance':'', 'Comment':'投稿者名', 'Type':'その他'},
  {'Id':'', 'Galar':'YFURe', 'Trance':'', 'Comment':'白い看板の2段目', 'Type':'看板'},
  {'Id':'', 'Galar':'YXRBSKHLDAMU', 'Trance':'', 'Comment':'白い看板の3段目', 'Type':'看板'},
  {'Id':'', 'Galar':'Khord', 'Trance':'', 'Comment':'主人公の部屋の箱', 'Type':'その他'},
  {'Id':'', 'Galar':'JCYU JVYU', 'Trance':'', 'Comment':'主人公の部屋のポスター', 'Type':'その他'},
  {'Id':'', 'Galar':'ZCISFHJ BhLL', 'Trance':'MONSTER BALL', 'Comment':'ホップの部屋のポスター', 'Type':'その他'},
  {'Id':'', 'Galar':'RLU', 'Trance':'', 'Comment':'ホップの部屋のタンスの上の箱', 'Type':'その他'},
  {'Id':'', 'Galar':'Dfkcq', 'Trance':'', 'Comment':'ポケモンフード \nエンジンシティのポスター \nダンデの部屋の段ボール', 'Type':'その他'},
  {'Id':'', 'Galar':'Oignfq', 'Trance':'', 'Comment':'ポケモンフード \n大コメント1', 'Type':'その他'},
  {'Id':'', 'Galar':'gm argqchao', 'Trance':'', 'Comment':'ポケモンフード \n1行目', 'Type':'その他'},
  {'Id':'', 'Galar':'Bkmorn gld', 'Trance':'', 'Comment':'ポケモンフード \n2行目', 'Type':'その他'},
  {'Id':'', 'Galar':'fkacr klq', 'Trance':'', 'Comment':'ポケモンフード \nメーカー名？', 'Type':'その他'},
  {'Id':'', 'Galar':'Nhgaidomrq', 'Trance':'', 'Comment':'バトルカフェの左メニュータイトル', 'Type':'その他'},
  {'Id':'', 'Galar':'Clmkin', 'Trance':'', 'Comment':'バトルカフェの左メニュー1', 'Type':'その他'},
  {'Id':'', 'Galar':'Xhdk', 'Trance':'', 'Comment':'バトルカフェの左メニュー2', 'Type':'その他'},
  {'Id':'', 'Galar':'Xhlk', 'Trance':'', 'Comment':'バトルカフェの左メニュー3', 'Type':'その他'},
  {'Id':'', 'Galar':'Aq', 'Trance':'', 'Comment':'バトルカフェの左メニュー4', 'Type':'その他'},
  {'Id':'', 'Galar':'Ckonrqlilanrcf', 'Trance':'', 'Comment':'バトルカフェの右メニュータイトル', 'Type':'その他'},
  {'Id':'', 'Galar':'Ronmlkqdhgrl', 'Trance':'', 'Comment':'バトルカフェの右メニュー1', 'Type':'その他'},
  {'Id':'', 'Galar':'ikmdalihak', 'Trance':'', 'Comment':'バトルカフェの右メニュー2', 'Type':'その他'},
  {'Id':'', 'Galar':'Agfrlkolai', 'Trance':'', 'Comment':'バトルカフェの右メニュー3', 'Type':'その他'},
  {'Id':'', 'Galar':'Ucidkaomhq', 'Trance':'', 'Comment':'バトルカフェの右メニュー4', 'Type':'その他'},
  {'Id':'', 'Galar':'kdcdkofkqhcao', 'Trance':'', 'Comment':'バトルカフェの右メニュー5', 'Type':'その他'},
  {'Id':'', 'Galar':'Xcgkdlfoli', 'Trance':'', 'Comment':'バトルカフェの右メニュー6', 'Type':'その他'},
  {'Id':'', 'Galar':'Dci', 'Trance':'', 'Comment':'バトルカフェの右メニューの値段？1', 'Type':'その他'},
  {'Id':'', 'Galar':'Clk', 'Trance':'', 'Comment':'バトルカフェの右メニューの値段？2', 'Type':'その他'},
  {'Id':'', 'Galar':'Yig', 'Trance':'', 'Comment':'バトルカフェの右メニューの値段？3', 'Type':'その他'},
  {'Id':'', 'Galar':'Ecg', 'Trance':'', 'Comment':'バトルカフェの右メニューの値段？4', 'Type':'その他'},
  {'Id':'', 'Galar':'Aq', 'Trance':'', 'Comment':'バトルカフェの右メニューの値段？5', 'Type':'その他'},
  {'Id':'', 'Galar':'Jqc', 'Trance':'', 'Comment':'バトルカフェの右メニューの値段？6', 'Type':'その他'},
  {'Id':'', 'Galar':'Bm', 'Trance':'', 'Comment':'バトルカフェの左メニューの値段？1', 'Type':'その他'},
  {'Id':'', 'Galar':'Sno', 'Trance':'', 'Comment':'バトルカフェの左メニューの値段？2', 'Type':'その他'},
  {'Id':'', 'Galar':'ohd', 'Trance':'', 'Comment':'バトルカフェの左メニューの値段？3', 'Type':'その他'},
  {'Id':'', 'Galar':'gio', 'Trance':'', 'Comment':'バトルカフェの左メニューの値段？4', 'Type':'その他'},
  {'Id':'', 'Galar':'Riqch', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章1', 'Type':'その他'},
  {'Id':'', 'Galar':'Kdq', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章2', 'Type':'その他'},
  {'Id':'', 'Galar':'Dhkm', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章3', 'Type':'その他'},
  {'Id':'', 'Galar':'eocd', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章4', 'Type':'その他'},
  {'Id':'', 'Galar':'Fmodn', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章5', 'Type':'その他'},
  {'Id':'', 'Galar':'Hkd', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章6', 'Type':'その他'},
  {'Id':'', 'Galar':'Lrlqc', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章7', 'Type':'その他'},
  {'Id':'', 'Galar':'Dci', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章8', 'Type':'その他'},
  {'Id':'', 'Galar':'Xh', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章9', 'Type':'その他'},
  {'Id':'', 'Galar':'Rlq', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章10', 'Type':'その他'},
  {'Id':'', 'Galar':'Kgcrmfki', 'Trance':'', 'Comment':'バトルカフェの左メニューの文章11', 'Type':'その他'},
  {'Id':'', 'Galar':'Dqhir', 'Trance':'', 'Comment':'美容院の中、ハサミの左 \n美容院の名前はこっちかも', 'Type':'その他'},
  {'Id':'', 'Galar':'aolmaf', 'Trance':'', 'Comment':'美容院の中、ハサミの右 \n美容院の名前はこっちかも', 'Type':'その他'},
  {'Id':'', 'Galar':'Khord', 'Trance':'', 'Comment':'美容院、関係者口？', 'Type':'その他'},
  {'Id':'', 'Galar':'AEF', 'Trance':'', 'Comment':'レコード屋の掘り出し物1', 'Type':''},
  {'Id':'', 'Galar':'REH', 'Trance':'', 'Comment':'レコード屋の掘り出し物2', 'Type':'その他'},
  {'Id':'', 'Galar':'GTKB', 'Trance':'', 'Comment':'レコード屋の掘り出し物3', 'Type':'その他'},
  {'Id':'', 'Galar':'AWSVE', 'Trance':'', 'Comment':'レコード屋の扉の札', 'Type':'その他'},
  {'Id':'', 'Galar':'Wclr', 'Trance':'', 'Comment':'美容院の外ガラス1段目 \nレジの盾にも同じ文字', 'Type':'その他'},
  {'Id':'', 'Galar':'ATU', 'Trance':'', 'Comment':'緑の看板、上の白いとこ1', 'Type':'看板'},
  {'Id':'', 'Galar':'MAI', 'Trance':'', 'Comment':'緑の看板、上の白いとこ2', 'Type':'看板'},
  {'Id':'', 'Galar':'LRE', 'Trance':'', 'Comment':'緑の看板、上の白いとこ3', 'Type':'看板'},
  {'Id':'', 'Galar':'OFDNJ', 'Trance':'', 'Comment':'緑の看板、メイン', 'Type':'看板'},
  {'Id':'', 'Galar':'SVECHM', 'Trance':'', 'Comment':'緑の看板、2段目', 'Type':'看板'},
  {'Id':'', 'Galar':'RHe?E DVSON AEFI', 'Trance':'', 'Comment':'緑の看板、最下段', 'Type':'看板'},
  {'Id':'', 'Galar':'Lgron', 'Trance':'', 'Comment':'預かり屋さん', 'Type':'会社名'},
  {'Id':'', 'Galar':'REYFBEO', 'Trance':'', 'Comment':'バウタウンのポスター左、1段目', 'Type':'その他'},
  {'Id':'', 'Galar':'mrih LMeJ', 'Trance':'', 'Comment':'バウタウンのポスター左、2段目', 'Type':'その他'},
  {'Id':'', 'Galar':'Agfrlkolai', 'Trance':'', 'Comment':'バウタウンのポスター左、3段目', 'Type':'その他'},
  {'Id':'', 'Galar':'IMFSFHL', 'Trance':'', 'Comment':'バウタウンのポスター右、1段目', 'Type':'その他'},
  {'Id':'', 'Galar':'mrih', 'Trance':'', 'Comment':'バウタウンのポスター右、2段目', 'Type':'その他'},
  {'Id':'', 'Galar':'c amrlq arko', 'Trance':'', 'Comment':'バウタウンのポスター右、3段目', 'Type':'その他'},
  {'Id':'', 'Galar':'CAEFBR', 'Trance':'', 'Comment':'防波亭前の立て看板 タイトル', 'Type':'その他'},
  {'Id':'', 'Galar':'Agfrlkolai', 'Trance':'', 'Comment':'防波亭前の立て看板 1行目', 'Type':'その他'},
  {'Id':'', 'Galar':'IMFSFHLC', 'Trance':'', 'Comment':'防波亭前の立て看板 2行目', 'Type':'その他'},
  {'Id':'', 'Galar':'Nhg？？？', 'Trance':'', 'Comment':'防波亭前の立て看板 3行目', 'Type':'その他'},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'防波亭前の立て看板 最後の', 'Type':'その他'},
  {'Id':'', 'Galar':'AMQTBSKH', 'Trance':'', 'Comment':'お得な掲示板 タイトル', 'Type':'その他'},
  {'Id':'', 'Galar':'BSKHL', 'Trance':'', 'Comment':'お得な掲示板 左1行目', 'Type':''},
  {'Id':'', 'Galar':'OFEDAMOQ', 'Trance':'', 'Comment':'お得な掲示板 左2行目', 'Type':''},
  {'Id':'', 'Galar':'LJCYIJ', 'Trance':'', 'Comment':'お得な掲示板 左3行目', 'Type':''},
  {'Id':'', 'Galar':'OFEDANV?', 'Trance':'', 'Comment':'お得な掲示板 左4行目', 'Type':''},
  {'Id':'', 'Galar':'DTWeNV?', 'Trance':'', 'Comment':'お得な掲示板 左5行目', 'Type':''},
  {'Id':'', 'Galar':'BSKHLeV', 'Trance':'', 'Comment':'お得な掲示板 左6行目', 'Type':''},
  {'Id':'', 'Galar':'TCYXDA', 'Trance':'', 'Comment':'お得な掲示板 左7行目', 'Type':''},
  {'Id':'', 'Galar':'AJCSKHLM', 'Trance':'', 'Comment':'お得な掲示板 左8行目', 'Type':''},
  {'Id':'', 'Galar':'KHLeV', 'Trance':'', 'Comment':'お得な掲示板 右1行目', 'Type':''},
  {'Id':'', 'Galar':'BSKHLeVi', 'Trance':'', 'Comment':'お得な掲示板 右2行目', 'Type':''},
  {'Id':'', 'Galar':'OFEDANV', 'Trance':'', 'Comment':'お得な掲示板 右3行目', 'Type':''},
  {'Id':'', 'Galar':'MUQTWY', 'Trance':'', 'Comment':'お得な掲示板 右4行目', 'Type':''},
  {'Id':'', 'Galar':'Ron', 'Trance':'', 'Comment':'バウタウンのレコード露店\nレコードタイトル', 'Type':''},
  {'Id':'', 'Galar':'Agf', 'Trance':'', 'Comment':'バウタウンのレコード露店\nレコードタイトル', 'Type':''},
  {'Id':'', 'Galar':'CAEF', 'Trance':'', 'Comment':'バウタウンのレコード露店\nレコードタイトル', 'Type':''},
  {'Id':'', 'Galar':'Uc', 'Trance':'', 'Comment':'バウタウンのレコード露店\nレコードタイトル', 'Type':''},
  {'Id':'', 'Galar':'Ofkc', 'Trance':'', 'Comment':'バウタウンのレコード露店\nレコードタイトル', 'Type':''},
  {'Id':'', 'Galar':'Nhgai', 'Trance':'', 'Comment':'バウタウンのレコード露店\nレコードタイトル', 'Type':''},
  {'Id':'', 'Galar':'REYF', 'Trance':'', 'Comment':'バウタウンのレコード露店\nレコードタイトル', 'Type':''},
  {'Id':'', 'Galar':'OYFRE', 'Trance':'', 'Comment':'バウタウンのレコード露店\nレコードタイトル', 'Type':''},
  {'Id':'', 'Galar':'Xcgk', 'Trance':'', 'Comment':'バウタウンのレコード露店\nケースのプレート', 'Type':''},
  {'Id':'', 'Galar':'Ronm', 'Trance':'', 'Comment':'バウタウンのレコード露店\nケースのプレート', 'Type':''},
  {'Id':'', 'Galar':'CAEF', 'Trance':'', 'Comment':'バウタウンのレコード露店\nケースのプレート', 'Type':''},
  {'Id':'', 'Galar':'Agfr', 'Trance':'', 'Comment':'バウタウンのレコード露店\nケースのプレート', 'Type':''},
  {'Id':'', 'Galar':'MBR', 'Trance':'', 'Comment':'ラテラルスタジアム横の標識\n左1行目', 'Type':''},
  {'Id':'', 'Galar':'Nlaiqdg', 'Trance':'', 'Comment':'ラテラルスタジアム横の標識\n左2行目', 'Type':''},
  {'Id':'', 'Galar':'Vdmq', 'Trance':'', 'Comment':'ラテラルスタジアム横の標識\n左3行目', 'Type':''},
  {'Id':'', 'Galar':'XrqYak', 'Trance':'', 'Comment':'ラテラルスタジアム横の標識\n左4行目', 'Type':''},
  {'Id':'', 'Galar':'RUOMF', 'Trance':'', 'Comment':'ラテラルスタジアム横の標識\n右1行目', 'Type':''},
  {'Id':'', 'Galar':'Urifrod', 'Trance':'', 'Comment':'ラテラルスタジアム横の標識\n右2行目', 'Type':''},
  {'Id':'', 'Galar':'Nnoiq', 'Trance':'', 'Comment':'ラテラルスタジアム横の標識\n右3行目', 'Type':''},
  {'Id':'', 'Galar':'DAFIA??', 'Trance':'', 'Comment':'アラベスクジムの舞台裏の貼り紙', 'Type':''},
  {'Id':'', 'Galar':'CAE??', 'Trance':'', 'Comment':'アラベスクジムの舞台裏の貼り紙', 'Type':''},
  {'Id':'', 'Galar':'XIU', 'Trance':'', 'Comment':'アラベスクジムの舞台裏の貼り紙', 'Type':''},
  {'Id':'', 'Galar':'Snoo', 'Trance':'', 'Comment':'アラベスクジムの舞台裏の貼り紙', 'Type':''},
  {'Id':'', 'Galar':'Dhkm', 'Trance':'', 'Comment':'キルクスの屋台', 'Type':''},
  {'Id':'', 'Galar':'iraolmai', 'Trance':'', 'Comment':'キルクスの屋台 上の文字', 'Type':''},
  {'Id':'', 'Galar':'Kgcrmfki', 'Trance':'', 'Comment':'キルクスの屋台 下の文字', 'Type':''},
  {'Id':'', 'Galar':'gqadf', 'Trance':'', 'Comment':'キルクスの屋台 立て看板', 'Type':''},
  {'Id':'', 'Galar':'Dhkm', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 左上タイトル1', 'Type':''},
  {'Id':'', 'Galar':'ilorg', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 左上タイトル2', 'Type':''},
  {'Id':'', 'Galar':'Xh', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上1', 'Type':''},
  {'Id':'', 'Galar':'Rlq', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上2', 'Type':''},
  {'Id':'', 'Galar':'Kgcrmfki', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上3', 'Type':''},
  {'Id':'', 'Galar':'Ecg', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上4', 'Type':''},
  {'Id':'', 'Galar':'Clk', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上5', 'Type':''},
  {'Id':'', 'Galar':'Fkri', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上6', 'Type':''},
  {'Id':'', 'Galar':'Urkqd', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上7', 'Type':''},
  {'Id':'', 'Galar':'Sno', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上8', 'Type':''},
  {'Id':'', 'Galar':'Traqaflk', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上9', 'Type':''},
  {'Id':'', 'Galar':'Ygciohlo', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上10', 'Type':''},
  {'Id':'', 'Galar':'Clmkin', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上11', 'Type':''},
  {'Id':'', 'Galar':'Traqaflk', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上12', 'Type':''},
  {'Id':'', 'Galar':'Ygciohlo', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左上13', 'Type':''},
  {'Id':'', 'Galar':'Mrkcg', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 左下タイトル', 'Type':''},
  {'Id':'', 'Galar':'Urkqd', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左下1', 'Type':''},
  {'Id':'', 'Galar':'Sno', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左下2', 'Type':''},
  {'Id':'', 'Galar':'Traqaflk', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左下3', 'Type':''},
  {'Id':'', 'Galar':'KkcnFgok', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左下4', 'Type':''},
  {'Id':'', 'Galar':'rifcagqn', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左下5', 'Type':''},
  {'Id':'', 'Galar':'amoqh', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左下6', 'Type':''},
  {'Id':'', 'Galar':'Yig', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左下7', 'Type':''},
  {'Id':'', 'Galar':'Vlohlmn', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左下8', 'Type':''},
  {'Id':'', 'Galar':'Ihld', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左下9', 'Type':''},
  {'Id':'', 'Galar':'Bm', 'Trance':'', 'Comment':'ステーキハウスのメニュー 左下10', 'Type':''},
  {'Id':'', 'Galar':'Rlq', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上タイトル', 'Type':''},
  {'Id':'', 'Galar':'ilorg', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上タイトル2', 'Type':''},
  {'Id':'', 'Galar':'Fmqdn', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上1', 'Type':''},
  {'Id':'', 'Galar':'Kkd', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上2', 'Type':''},
  {'Id':'', 'Galar':'Lrlqc', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上3', 'Type':''},
  {'Id':'', 'Galar':'Dci', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上4', 'Type':''},
  {'Id':'', 'Galar':'Mrkcg', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上5', 'Type':''},
  {'Id':'', 'Galar':'Vlohlmn', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上6', 'Type':''},
  {'Id':'', 'Galar':'Ihld', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上7', 'Type':''},
  {'Id':'', 'Galar':'Xh', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上8', 'Type':''},
  {'Id':'', 'Galar':'Rlq', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上9', 'Type':''},
  {'Id':'', 'Galar':'Kgcrmfki', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中上10', 'Type':''},
  {'Id':'', 'Galar':'Dci', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中下タイトル', 'Type':''},
  {'Id':'', 'Galar':'Riqch', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中下1', 'Type':''},
  {'Id':'', 'Galar':'Kdq', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中下2', 'Type':''},
  {'Id':'', 'Galar':'Dhkm', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中下3', 'Type':''},
  {'Id':'', 'Galar':'eocd', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中下4', 'Type':''},
  {'Id':'', 'Galar':'Urkqd', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中下5', 'Type':''},
  {'Id':'', 'Galar':'Sno', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中下6', 'Type':''},
  {'Id':'', 'Galar':'Traqaflk', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中下7', 'Type':''},
  {'Id':'', 'Galar':'Yg', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中下8', 'Type':''},
  {'Id':'', 'Galar':'Kgcrmfki', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 真ん中下9', 'Type':''},
  {'Id':'', 'Galar':'rifcagqn', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 右タイトル', 'Type':''},
  {'Id':'', 'Galar':'Traqaflk', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 右上タイトル', 'Type':''},
  {'Id':'', 'Galar':'Mrkcg', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右上1', 'Type':''},
  {'Id':'', 'Galar':'Vlohlmn', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右上2', 'Type':''},
  {'Id':'', 'Galar':'Ihld', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右上3', 'Type':''},
  {'Id':'', 'Galar':'Dhkm', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右上4', 'Type':''},
  {'Id':'', 'Galar':'eocd', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右上5', 'Type':''},
  {'Id':'', 'Galar':'Nkihd', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右上6', 'Type':''},
  {'Id':'', 'Galar':'Wclr', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右上7', 'Type':''},
  {'Id':'', 'Galar':'Dci eom', 'Trance':'', 'Comment':'ステーキハウスのメニュー \n 右下タイトル', 'Type':''},
  {'Id':'', 'Galar':'Jqc', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右下1', 'Type':''},
  {'Id':'', 'Galar':'Orfko', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右下2', 'Type':''},
  {'Id':'', 'Galar':'Xhdk', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右下3', 'Type':''},
  {'Id':'', 'Galar':'fcigKl', 'Trance':'', 'Comment':'ステーキハウスのメニュー 右下4', 'Type':''},
  {'Id':'', 'Galar':'Dhkm', 'Trance':'', 'Comment':'スパイクタウンのネオン1', 'Type':''},
  {'Id':'', 'Galar':'RFQIN DeVYr', 'Trance':'', 'Comment':'マリィのポスター', 'Type':''},
  {'Id':'', 'Galar':'UXWJNLT', 'Trance':'', 'Comment':'マリィのポスター2', 'Type':''},
  {'Id':'', 'Galar':'Lgron', 'Trance':'', 'Comment':'スパイクタウンの落書き1', 'Type':''},
  {'Id':'', 'Galar':'Orfko', 'Trance':'', 'Comment':'スパイクタウンのネオン2', 'Type':''},
  {'Id':'', 'Galar':'Doh', 'Trance':'', 'Comment':'スパイクタウンの落書き2', 'Type':''},
  {'Id':'', 'Galar':'Rlq', 'Trance':'', 'Comment':'スパイクタウンの落書き3', 'Type':''},
  {'Id':'', 'Galar':'QCRqZCI', 'Trance':'POKEMON', 'Comment':'スパイクタウンのネオン3\nPOKがポケジョブと同じ\nMONがホップの部屋のポスターと同じ', 'Type':''},
  {'Id':'', 'Galar':'DO', 'Trance':'GO', 'Comment':'スパイクタウンのネオン4\n上のと合わせてPokémonGOか', 'Type':''},
  {'Id':'', 'Galar':'earig', 'Trance':'', 'Comment':'スパイクタウンのネオン5', 'Type':''},
  {'Id':'', 'Galar':'???', 'Trance':'', 'Comment':'スパイクタウンのネオン6 \n筆記体で読めない', 'Type':''},
  {'Id':'', 'Galar':'Mrk', 'Trance':'', 'Comment':'スパイクタウンのネオン7', 'Type':''},
  {'Id':'', 'Galar':'Uqg Srgcl', 'Trance':'', 'Comment':'スパイクタウンのネオン8\nギターのやつ', 'Type':''},
  {'Id':'', 'Galar':'Jnlmo', 'Trance':'', 'Comment':'スパイクタウンのネオン9 \nヤミラミのやつ', 'Type':''},
  {'Id':'', 'Galar':'ohd Xhdkf', 'Trance':'', 'Comment':'スパイクタウンのネオン10', 'Type':''},
  {'Id':'', 'Galar':'WSILYJWCRVe', 'Trance':'', 'Comment':'スパイク商工会の幕のカラフルなやつ', 'Type':''},
  {'Id':'', 'Galar':'Dci', 'Trance':'', 'Comment':'スパイクタウンのネオン11', 'Type':''},
  {'Id':'', 'Galar':'EHKLCCU OWS', 'Trance':'', 'Comment':'スパイクタウンのポスター1', 'Type':''},
  {'Id':'', 'Galar':'Agfrlkolai', 'Trance':'', 'Comment':'スパイクタウンの白い看板', 'Type':''},
  {'Id':'', 'Galar':'WSILYJ VXDA', 'Trance':'', 'Comment':'スパイクタウンの入り口(シャッター横)', 'Type':''},
  {'Id':'', 'Galar':'NBIHTOFI', 'Trance':'', 'Comment':'スパイクジム入り口付近のポスター手前\nタイトル', 'Type':''},
  {'Id':'', 'Galar':'Oan Lqdo', 'Trance':'', 'Comment':'スパイクジム入り口付近のポスター手前\n2段目', 'Type':''},
  {'Id':'', 'Galar':'Mdghm', 'Trance':'', 'Comment':'スパイクジム入り口付近のポスター手前\n3段目', 'Type':''},
  {'Id':'', 'Galar':'DWeLMeJ', 'Trance':'', 'Comment':'スパイクジム入り口付近のポスター手前\n真ん中', 'Type':''},
  {'Id':'', 'Galar':'UKLEX', 'Trance':'', 'Comment':'スパイクジム入り口付近のポスター手前\n奥', 'Type':''},
  {'Id':'', 'Galar':'ReYITKR', 'Trance':'', 'Comment':'ナックルジムのショップカウンター', 'Type':''},
  {'Id':'', 'Galar':'dha', 'Trance':'', 'Comment':'エネルギープラントの入り口', 'Type':''},
  {'Id':'', 'Galar':'MUQTWYXR', 'Trance':'', 'Comment':'エネルギープラントの入り口 2段目', 'Type':''},
  {'Id':'', 'Galar':'OIVECX', 'Trance':'', 'Comment':'エネルギープラント \n 入ってすぐのプレート', 'Type':''},
  {'Id':'', 'Galar':'BSKHLeVI', 'Trance':'', 'Comment':'エネルギープラント \n 入ってすぐのプレート1段目', 'Type':''},
  {'Id':'', 'Galar':'OFEDANV', 'Trance':'', 'Comment':'エネルギープラント \n 入ってすぐのプレート2段目', 'Type':''},
  {'Id':'', 'Galar':'OFEDANVIJCYDAMUQT', 'Trance':'', 'Comment':'エネルギープラント \n 入ってすぐのプレート3段目', 'Type':''},
  {'Id':'', 'Galar':'BSKHLeNVIJCYXR', 'Trance':'', 'Comment':'エネルギープラント \n 入ってすぐのプレート4段目', 'Type':''},
  {'Id':'', 'Galar':'OFEDAMUQTW', 'Trance':'', 'Comment':'エネルギープラント \n 入ってすぐのプレート5段目', 'Type':''},
  {'Id':'', 'Galar':'Ofkrnikdl', 'Trance':'', 'Comment':'エネルギープラント\n←の文/エレベーター？', 'Type':''},
  {'Id':'', 'Galar':'Lordagm', 'Trance':'', 'Comment':'エネルギープラント\n→の文/入り口？', 'Type':''},
  {'Id':'', 'Galar':'EFBReYI', 'Trance':'', 'Comment':'エネルギープラント\nエレベーター前のプレート1', 'Type':''},
  {'Id':'', 'Galar':'BSKHLeNVIJC', 'Trance':'', 'Comment':'エネルギープラント\nエレベーター前のプレート2', 'Type':''},
  {'Id':'', 'Galar':'OFEDAMUQTW', 'Trance':'', 'Comment':'エネルギープラント\nエレベーター前のプレート3', 'Type':''},
  {'Id':'', 'Galar':'KHLeVIJCYXD', 'Trance':'', 'Comment':'エネルギープラント\nエレベーター前のプレート4', 'Type':''},
  {'Id':'', 'Galar':'OFEDANVIJC', 'Trance':'', 'Comment':'エネルギープラント\nエレベーター前のプレート5', 'Type':''},
  {'Id':'', 'Galar':'NVIJ', 'Trance':'', 'Comment':'エネルギープラント内の赤いゲート', 'Type':''},
  {'Id':'', 'Galar':'TWYXR', 'Trance':'', 'Comment':'エネルギープラント\nムゲンダイナにねがいぼしを与えてた装置', 'Type':''},
  {'Id':'', 'Galar':'LUNIH', 'Trance':'', 'Comment':'エネルギープラントの会社名？', 'Type':''},
  {'Id':'', 'Galar':'FALE', 'Trance':'', 'Comment':'シュートジムの前のタクシー', 'Type':''},
  {'Id':'', 'Galar':'RKCM', 'Trance':'', 'Comment':'シュートジムの前のタクシー\nナンバープレート', 'Type':''},
  {'Id':'', 'Galar':'Nhgaidom', 'Trance':'', 'Comment':'シュートジム前の屋台\nあおのとこ\n公式グッズ', 'Type':''},
  {'Id':'', 'Galar':'Jnlmo', 'Trance':'', 'Comment':'シュートジム前の屋台\nピンクのとこ', 'Type':''},
  {'Id':'', 'Galar':'Tkrqng', 'Trance':'', 'Comment':'シュートジム前の屋台\nオレンジのとこ', 'Type':''},
  {'Id':'', 'Galar':'Urkqd', 'Trance':'', 'Comment':'シュートジム前の屋台\n水色のとこ\nドリンク屋', 'Type':''},
  {'Id':'', 'Galar':'REYF', 'Trance':'', 'Comment':'シュートジム前の屋台\nホワイトボード1', 'Type':''},
  {'Id':'', 'Galar':'EOIVBMSDAFIAK', 'Trance':'', 'Comment':'シュートジム前の屋台\nホワイトボード2', 'Type':''},
  {'Id':'', 'Galar':'IMFSFHLCR', 'Trance':'', 'Comment':'シュートジム前の屋台\nホワイトボード3', 'Type':''},
  {'Id':'', 'Galar':'OYFREHFLU', 'Trance':'', 'Comment':'シュートジム前の屋台\nホワイトボード4', 'Type':''},
  {'Id':'', 'Galar':'Mdrg q dif', 'Trance':'', 'Comment':'バトルタワーのタブレット', 'Type':''},
  {'Id':'', 'Galar':'Nmqfol', 'Trance':'', 'Comment':'バトルタワー受付のパネル', 'Type':''},
  {'Id':'', 'Galar':'DEKRXCKSIH', 'Trance':'', 'Comment':'バトルタワーのエレベーター横\nフロア案内1', 'Type':''},
  {'Id':'', 'Galar':'Uhdmn VrqaImo', 'Trance':'', 'Comment':'バトルタワーのエレベーター横\nフロア案内2', 'Type':''},
  {'Id':'', 'Galar':'VdlIaiq Jhaork', 'Trance':'', 'Comment':'バトルタワーのエレベーター横\nフロア案内3', 'Type':''},
  {'Id':'', 'Galar':'Ohmr WBioqf', 'Trance':'', 'Comment':'バトルタワーのエレベーター横\nフロア案内4', 'Type':''},
  {'Id':'', 'Galar':'Lilolrm IcdEal', 'Trance':'', 'Comment':'バトルタワーのエレベーター横\nフロア案内5', 'Type':''},
  {'Id':'', 'Galar':'MVrho Colkqk', 'Trance':'', 'Comment':'バトルタワーのエレベーター横\nフロア案内6', 'Type':''},
  {'Id':'', 'Galar':'MVrho WBioqf', 'Trance':'', 'Comment':'バトルタワーのエレベーター横\nフロア案内7', 'Type':''},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'バトルカフェのごみ箱左', 'Type':''},
  {'Id':'', 'Galar':'', 'Trance':'', 'Comment':'バトルカフェのごみ箱右', 'Type':''},
  {'Id':'', 'Galar':'GALAJ Bdfirg', 'Trance':'', 'Comment':'エネルギープラントの解説\n上のピンク1', 'Type':''},
  {'Id':'', 'Galar':'Xhdk fcig', 'Trance':'', 'Comment':'エネルギープラントの解説\n上のピンク2', 'Type':''},
  {'Id':'', 'Galar':'GALAJ Bdfirg', 'Trance':'', 'Comment':'エネルギープラントの解説\n左のピンク', 'Type':''},
  {'Id':'', 'Galar':'UEXMF Vqdamon', 'Trance':'', 'Comment':'エネルギープラントの解説\n下のオレンジ', 'Type':''},
  {'Id':'', 'Galar':'Ofkcrnikdl', 'Trance':'', 'Comment':'エネルギープラントの解説\n下の青1', 'Type':''},
  {'Id':'', 'Galar':'BKSe', 'Trance':'', 'Comment':'エネルギープラントの解説\n下の青2', 'Type':''},
  {'Id':'', 'Galar':'UEXMF DNoM', 'Trance':'', 'Comment':'エネルギープラントの解説\n下の黄色', 'Type':''},
  {'Id':'', 'Galar':'GALAJ Bdfirg', 'Trance':'', 'Comment':'エネルギープラントの解説\nローズの吹き出し1', 'Type':''},
  {'Id':'', 'Galar':'Vm Clmkin qgdi', 'Trance':'', 'Comment':'エネルギープラントの解説\nローズの吹き出し2', 'Type':''},
  {'Id':'', 'Galar':'ROSH UeNCVIY', 'Trance':'', 'Comment':'エネルギープラントの解説\nローズの吹き出し3', 'Type':''},
  {'Id':'', 'Galar':'DNoM hqlJNo VVadS', 'Trance':'', 'Comment':'エネルギープラントの解説\nローズの吹き出し4', 'Type':''},
  {'Id':'', 'Galar':'ROSH UeNCVIY', 'Trance':'', 'Comment':'エネルギープラントの解説\nローズ カンパニー？', 'Type':''},
  {'Id':'', 'Galar':'eqoca ROSH', 'Trance':'', 'Comment':'エネルギープラントの解説\n役職とローズ', 'Type':''},
  {'Id':'', 'Galar':'OIVECX', 'Trance':'', 'Comment':'ソニアの研究所\n紙袋の横のボード', 'Type':''},
  {'Id':'', 'Galar':'Agfrlk', 'Trance':'', 'Comment':'ソニアの研究所\n紙袋の横のボード2', 'Type':''},
  {'Id':'', 'Galar':'TKR', 'Trance':'', 'Comment':'ソニアの研究所\nなにかを測定してるデータ1', 'Type':''},
  {'Id':'', 'Galar':'CXe', 'Trance':'', 'Comment':'ソニアの研究所\nなにかを測定してるデータ2', 'Type':''},
  {'Id':'', 'Galar':'DAF', 'Trance':'', 'Comment':'ソニアの研究所\nなにかを測定してるデータ3', 'Type':''},
  {'Id':'', 'Galar':'SNODWeL', 'Trance':'', 'Comment':'ソニアの研究所\nなにかを測定してるデータ4', 'Type':''},
  {'Id':'', 'Galar':'FeeKUJVYU', 'Trance':'', 'Comment':'ソニアの研究所\nホワイトボードのマップ', 'Type':''},
  {'Id':'', 'Galar':'KOYXOH', 'Trance':'', 'Comment':'ソニアの部屋\n枕元のマップ', 'Type':''},
  {'Id':'', 'Galar':'BMSDA', 'Trance':'', 'Comment':'ソニアの部屋\nコルクボード', 'Type':''},
  {'Id':'', 'Galar':'FLUN', 'Trance':'', 'Comment':'ホップの部屋のポスター', 'Type':''},
  {'Id':'', 'Galar':'CAEFBReYITKR', 'Trance':'', 'Comment':'ポケモンセンター\n回復時に表示される文字右1', 'Type':''},
  {'Id':'', 'Galar':'MFSFHLC', 'Trance':'', 'Comment':'ポケモンセンター\n回復時に表示される文字右2', 'Type':''},
  {'Id':'', 'Galar':'OYFREHFLU', 'Trance':'', 'Comment':'ポケモンセンター\n回復時に表示される文字右3', 'Type':''},
  {'Id':'', 'Galar':'UNIHCAK', 'Trance':'', 'Comment':'ポケモンセンター\n回復時に表示される文字左\nランダム1', 'Type':''},
  {'Id':'', 'Galar':'OIVECXeN', 'Trance':'', 'Comment':'ポケモンセンター\n回復時に表示される文字左\nランダム2', 'Type':''},
  {'Id':'', 'Galar':'MSDAFIAK', 'Trance':'', 'Comment':'ポケモンセンター\n回復時に表示される文字左\nランダム3', 'Type':''},
  {'Id':'', 'Galar':'HLCRSE', 'Trance':'', 'Comment':'ポケモンセンター\n回復時に表示される文字左\nランダム4', 'Type':''},
  {'Id':'', 'Galar':'OFEDANVSJCYDAMUQT', 'Trance':'', 'Comment':'スパイクタウン宝物庫\n受付のプレート1', 'Type':''},
  {'Id':'', 'Galar':'BSKHLeAVDJCYXR', 'Trance':'', 'Comment':'スパイクタウン宝物庫\n受付のプレート2', 'Type':''},
  {'Id':'', 'Galar':'OFEDAMUQTW', 'Trance':'', 'Comment':'スパイクタウン宝物庫\n受付のプレート3', 'Type':''},
  {'Id':'', 'Galar':'RAW', 'Trance':'', 'Comment':'レトルトめん', 'Type':'しょくざい'},
  {'Id':'', 'Galar':'USEHR', 'Trance':'', 'Comment':'カレンダー', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'nBledFJh', 'Trance':'', 'Comment':'カレンダー', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'KSHln', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'LMKR', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'BnedJ', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'TgCO', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'CV?T', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'D?C?', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'lr?h', 'Trance':'', 'Comment':'曜日', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'earig Dqh', 'Trance':'', 'Comment':'ポスター左上1行目', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'ir aolmaf', 'Trance':'', 'Comment':'ポスター左上2行目', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'Lorda oqg', 'Trance':'', 'Comment':'ポスター左上3行目', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'Xh Rlq Kgcrmfki', 'Trance':'', 'Comment':'ポスター左下', 'Type':'スタジオコロリドTwitter'},
  {'Id':'', 'Galar':'SiN', 'Trance':'', 'Comment':'飲み物', 'Type':'スタジオコロリドTwitter'},
];

const types = [
  '地名', '人名', 'ユニフォーム', '薄明の翼',
];

// new Vue({
//   el: '#app',
//   data () {
//     return {
//       info: null
//     }
//   },
//   mounted () {
//     axios
//       .get('https://script.google.com/macros/s/AKfycbwiBx_4iRiaYQVKGeunDISwy8IMMn9-qSgNmYhFzZUb2GTrFoBz3l4/exec')
//       .then(response => {
//         this.info = response.data
//       })
//   }
// })
new Vue({
  el: '#app',
  data: {
    items: items,
    sort: {
      key: '', // ソートキー
      isAsc: false // 昇順ならtrue,降順ならfalse
    },
    // types: types,       // チェックボックスの値
    // selectTypes: types,  // 選択されたチェックボックスの値
    searchGalar: '',   // 入力された文字列を格納
  },
  computed: {
    eventedAction: function() {
      let list = this.items.slice();

      // ソート実施
      if(this.sort.key) {
        list.sort((a, b) => {
          a = a[this.sort.key];
          b = b[this.sort.key];
          return (a === b ? 0 : a > b ? 1 : -1) * (this.sort.isAsc ? 1 : -1);
        });
      }
      // // Typeでフィルタリング実施
      // if(this.selectTypes) {
      //   list = list.filter(element => {
      //     for(const type of this.selectTypes) {
      //       if(element.Type === type) {
      //         return true;
      //       }
      //     }
      //   });
      // }
      // Nameで検索実施
      if (this.searchGalar) {
        list = list.filter(element => {
          return Object.keys(element).some(key => {
            if(key === 'Galar') {
              return element[key].indexOf(this.searchGalar) > -1;
            }
          });
        });
      }

      return list;
    }   
  },
  methods: {
    // sort用キーをセットし、昇順・降順を入れ替える
    sortBy: function(key) {
      this.sort.isAsc = this.sort.key === key ? !this.sort.isAsc : false;
      this.sort.key = key;
    },
    sortedClass: function(key) {
      return this.sort.key === key ? `sorted ${this.sort.isAsc ? 'asc' : 'desc' }` : '';
    },
    // 全ての処理をクリアする
    resetting: function() {
      this.sort.key = '';
      this.sort.isAsc = false;
      // this.selectTypes = types;
      this.searchGalar = '';
      this.items = items;
    }
  }
});